### ISSUE TITLE
Start in system tray only

### ISSUE THREAD

**Issue by tengl** [timothycrosley/streamdeck-ui#10]
Thanks for a great tool.

Is there a way to start the app minimized to the system tray directly? If not, that would be a really nice feature.

**Comment by obook** [comment]
You can edit the gui.py file, in my case is .local/lib/python3.8/site-packages/streamdeck_ui/gui.py and comment the line 284 :

`# main_window.show()`

Regards,
Olivier

**Comment by dodgyrabbit** [comment]
This has been implemented.

**Comment by Herfen** [comment]
Ehish that would work on Manjaro KDE
