### ISSUE TITLE
Feature request : name of QMainWindow (gui.py)

### ISSUE THREAD

**Issue by obook** [timothycrosley/streamdeck-ui#102]
It will be cool to set the QMainWindow name ...

File : streamdeck-ui/streamdeck_ui/gui.py
Line 210 add : 

`
self.setWindowTitle("StreamDeck UI")
`

Anyway thx for this wonderful program for my new StreamDeck.

Regards

**Comment by dodgyrabbit** [comment]
FYI there is a [PR](https://github.com/timothycrosley/streamdeck-ui/pull/26) with this feature in the pipeline

Specifically [this commit](https://github.com/timothycrosley/streamdeck-ui/pull/26/commits/f26db9cd7d986ee2da5a1b47e3fc74ab19aad9c2)

Based on the long list of PRs and growing list of issues, I think your best bet is to fork and incorporate the changes you want. Doesn't seem like this project is getting a lot of love from the owner right now - [bigger fish to fry](https://github.com/timothycrosley)?

**Comment by dodgyrabbit** [comment]
This has been implemented.
