### ISSUE TITLE
Security: screensaver bypass

### ISSUE THREAD

**Issue by DavidFromNL** [timothycrosley/streamdeck-ui#103]
First, thanks for creating this awesome software!

I found an issue however that may be a security issue. When the computer is locked/the screensaver is running*, streamdeck-ui still allows every action to continue as if the computer were unlocked. While there is a good reason for some buttons to keep working (for example if you hooked the stream deck to your domotica), some buttons may trigger undesired/insecure actions. Especially the keystrokes, which are not sent to the screensaver but to any program running behind the screensaver instead, pose a security thread.

I think it would be a good idea to check if the screensaver is running with every action, and only allow those actions that have a checkbox set.

* This is at least the case on Cinnamon/Gnome3.

**Comment by desrod** [comment]
> I think it would be a good idea to check if the screensaver is running with every action, and only allow those actions that have a checkbox set.

The bigger issue is... which screensaver? There are several different apps out there that provide 'locking' capability, not limited to screensaver. You've also got to deal with an X/Wayland session that isn't locked, but where you're in another context, such as Ctrl-Alt-F3 console away from your graphical session. 

I agree, something should be added here as a check, but done in a generic way to avoid having to cover many unique edge cases.

**Comment by DavidFromNL** [comment]
I'm using the default Cinnamon screensaver. I just found this code to be able to tell if my screensaver is running:
```
import dbus
def screensaver_status():
    session_bus = dbus.SessionBus()
    screensaver_list = ['org.gnome.ScreenSaver', 'org.cinnamon.ScreenSaver', 'org.kde.screensaver', org.freedesktop.ScreenSaver']
    for each in screensaver_list:
        try:
            object_path = '/{0}'.format(each.replace('.', '/'))
            get_object = session_bus.get_object(each, object_path)
            get_interface = dbus.Interface(get_object, each)
            return bool(get_interface.GetActive())
        except dbus.exceptions.DBusException:
            pass
```

I haven't been able to test it, but I believe this will work with KDE, Gnome and pretty much any other Linux screensaver.

**Comment by dodgyrabbit** [comment]
Thanks for the code snippet, will look into detecting this via dbus.
Closing this as a duplicate of #46 and we'll deal with it there.
