### ISSUE TITLE
Remove icon button blank

### ISSUE THREAD

**Issue by tylerjw** [timothycrosley/streamdeck-ui#110]
![20210401_080917](https://user-images.githubusercontent.com/2490389/113306721-9e78ea80-92c1-11eb-8737-3313f5526456.png)

I'm not sure if this should have an icon or something but it is blank for me.

Version: 1.0.4
OS: Ubuntu 20.04
WM: i3

**Comment by dodgyrabbit** [comment]
Please try version 1.0.5 and verify that the icon is showing up for you.

**Comment by dodgyrabbit** [comment]
The icon issue is fixed in 1.0.5
