### ISSUE TITLE
Chaining multiple commands with logical operators

### ISSUE THREAD

**Issue by t3838d4** [timothycrosley/streamdeck-ui#111]
I have installed the 1.0.4 test release and it works much better with command line arguments, thanks for fixing the argument quoting issues with 1.0.3

I have another issue/question - would it be possible to use logical operators && and || when defining commands?
Currently these do not work

For example, I have defined some buttons like this: 
```json
"22": {
    "text": "TEST",
    "command": "notify-send \"Test notify from Stream Deck\" && notify-send \"Test notify 2 from Stream Deck\""
},
"23": {
    "text": "TEST 2",
    "command": "wmctrl -a TryToActivateNonexistentWindowAndAlwaysReturnFalse || notify-send \"Test notify 3 from Stream Deck\""
},
```
All these 4 commands work independently as expected, but not when combined with && or ||

**Comment by dodgyrabbit** [comment]
I'd say the best option is to write small script that chains the commands you want and run that script instead.
The command option just spawns a processes using the arguments supplied. The && and || operators are normally handled by the shell, so can't think of an easy way to build this into streamdeck-ui - and probably not something we want to do.

FYI I've been tinkering with another solution where we can chain multiple actions when pressing a button, which would effectively mean you can run a series of commands or other actions (keypress and custom actions). However, this is still a WIP and right now focus is to just get a stable and updated build out.

**Comment by tylerjw** [comment]
You could always do this (this will pass this string as commands into bash):

```
"23": {
    "text": "TEST 2",
    "command": "bash -c 'wmctrl -a TryToActivateNonexistentWindowAndAlwaysReturnFalse || notify-send \"Test notify 3 from Stream Deck\"'"
},
```

**Comment by t3838d4** [comment]
>     "command": "bash -c 'wmctrl -a TryToActivateNonexistentWindowAndAlwaysReturnFalse || notify-send \"Test notify 3 from 

Ok, thank you very much, somehow slipped my mind :)
