### ISSUE TITLE
Core dump on exit - Manjaro 21 + XFCE

### ISSUE THREAD

**Issue by dodgyrabbit** [timothycrosley/streamdeck-ui#112]
@dodgyrabbit 

My System: 
Manjaro 21.0 XFCE but modified to run with bspwm. 
There is a Manjaro bspwm 20.0.1 community edition: https://manjaro.org/download/#bspwm
Unfortunately i had no time spinning up a clean install of either to try. (Perhaps i'll get to this later today)

I have a Stream Deck Original (V2) - it's the only one attached through a USB Hub.

Below 3 more logs:
`python -u -m trace -t` on the up2date master branch:

```
api.py(167):             deck.close()
 --- modulename: StreamDeck, funcname: close
StreamDeck.py(159):         self.device.close()
 --- modulename: LibUSBHIDAPI, funcname: close
LibUSBHIDAPI.py(357):             if self.device_handle:
LibUSBHIDAPI.py(358):                 self.hidapi.close_device(self.device_handle)
 --- modulename: LibUSBHIDAPI, funcname: close_device
LibUSBHIDAPI.py(193):             if handle:
LibUSBHIDAPI.py(194):                 with self.mutex:
LibUSBHIDAPI.py(195):                     self.hidapi.hid_close(handle)
StreamDeck.py(111):                     continue
StreamDeck.py(106):         while self.run_read_thread:
StreamDeck.py(107):             try:
StreamDeck.py(108):                 new_key_states = self._read_key_states()
 --- modulename: StreamDeckOriginalV2, funcname: _read_key_states
StreamDeckOriginalV2.py(84):         states = self.device.read(4 + self.KEY_COUNT)
 --- modulename: LibUSBHIDAPI, funcname: read
LibUSBHIDAPI.py(436):             return self.hidapi.read(self.device_handle, length)
 --- modulename: LibUSBHIDAPI, funcname: read
LibUSBHIDAPI.py(295):             if not handle:
LibUSBHIDAPI.py(298):             data = ctypes.create_string_buffer(length)
 --- modulename: __init__, funcname: create_string_buffer
__init__.py(53):     if isinstance(init, bytes):
__init__.py(61):     elif isinstance(init, int):
__init__.py(62):         _sys.audit("ctypes.create_string_buffer", None, init)
__init__.py(63):         buftype = c_char * init
__init__.py(64):         buf = buftype()
__init__.py(65):         return buf
LibUSBHIDAPI.py(300):             with self.mutex:
LibUSBHIDAPI.py(359):                 self.device_handle = None
api.py(165):     for _deck_serial, deck in decks.items():
gui.py(390):         sys.exit()
LibUSBHIDAPI.py(301):                 result = self.hidapi.hid_read(handle, data, len(data))
LibUSBHIDAPI.py(303):             if result < 0:
LibUSBHIDAPI.py(304):                 raise TransportError("Failed to read in report (%d)" % result)
StreamDeck.py(119):             except (TransportError):
StreamDeck.py(120):                 self.run_read_thread = False
StreamDeck.py(106):         while self.run_read_thread:
threading.py(896):             del self._target, self._args, self._kwargs
[1]    40469 segmentation fault (core dumped)  python -u -m trace -t 
```
and

```
LibUSBHIDAPI.py(300):             with self.mutex:
LibUSBHIDAPI.py(359):                 self.device_handle = None
LibUSBHIDAPI.py(301):                 result = self.hidapi.hid_read(handle, data, len(data))
LibUSBHIDAPI.py(303):             if result < 0:
LibUSBHIDAPI.py(304):                 raise TransportError("Failed to read in report (%d)" % result)
StreamDeck.py(119):             except (TransportError):
StreamDeck.py(120):                 self.run_read_thread = False
StreamDeck.py(106):         while self.run_read_thread:
threading.py(896):             del self._target, self._args, self._kwargs
api.py(165):     for _deck_serial, deck in decks.items():
gui.py(390):         sys.exit()
```

`strace streamdeck` on  1.0.6 installed via pip3

```
munmap(0x7fca700cf000, 5034400)         = 0
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{iov_base="<\0\2\0\30\0\240\0006\0\2\0\27\0\240\0\206\6\2\0\20\0\240\0\4\0\2\0\17\0\240\0"..., iov_len=68}], 1) = 68
futex(0x560914560df8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fff709548d8, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, FUTEX_BITSET_MATCH_ANY) = 0
futex(0x560914560df8, FUTEX_WAKE_PRIVATE, 1) = 0
munmap(0x7fcaafaa6000, 1024)            = 0
futex(0x5609147331c4, FUTEX_WAKE_PRIVATE, 2147483647) = 1
futex(0x560914733170, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560914725930, FUTEX_WAKE_PRIVATE, 2147483647) = 1
futex(0x5609147258e0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x56091475eed4, FUTEX_WAKE_PRIVATE, 2147483647) = 1
futex(0x56091475ee80, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560914930644, FUTEX_WAKE_PRIVATE, 2147483647) = 1
futex(0x5609149305f0, FUTEX_WAKE_PRIVATE, 1) = 1
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x8} ---
+++ killed by SIGSEGV (core dumped) +++
[1]    40688 segmentation fault (core dumped)  strace streamdeck

```

Related to the `TransportError`?

Thanks btw for all the updates!

_Originally posted by @delpes in https://github.com/timothycrosley/streamdeck-ui/issues/109#issuecomment-812880823_

**Comment by dodgyrabbit** [comment]
@delpes Moving this to a separate issue.

I installed Arch Linux in a VM with XFCE and got streamdeck working. However, I could not reproduce the core dump.
For the USB interface, I installed `hidapi`.

Stab in the dark, but could we compare versions?

``` console
$ pacman -Q hidapi
hidapi 0.10.1-1
```

**Comment by dodgyrabbit** [comment]
> it's the only one attached through a USB Hub.

Could you try use it without the hub? There were some people reporting issues and Elgato also has some [info](https://help.elgato.com/hc/en-us/articles/360028233331-Elgato-Stream-Deck-Using-USB-Cable-Extensions). May or may not be relevant but worth eliminating the variable.

**Comment by dodgyrabbit** [comment]
I ran a python trace on my system and compared the two.
Left side is the failing one, right side is normal exit.

Still trying to make sense of it, but some observations so far:

- In mine, after the device is closed the Handle is set to None. This alters the behavior further down.
- In yours, the code continues to run in StreamDeck.py (which is running on a separate thread in [_read](https://github.com/abcminiuser/python-elgato-streamdeck/blob/f48a4012cf48ce4f64b2c576e892a6bcd5c6f185/src/StreamDeck/Devices/StreamDeck.py#L100))
- Then, the handle is set to None (line 30, highlighted)
- The very next moment, LibUSBHIDAPI.py tries to read, gets an error and throws

Perhaps the core dump is because it tried to read from an already closed handle.

This would seem to me to be a race condition in the streamdeck library between one thread closing the device and the read loop still trying to read key states.

![image](https://user-images.githubusercontent.com/518187/113490699-c7ec6e80-9499-11eb-8dd2-51c2a1d74c8c.png)

**Comment by delpes** [comment]
Thank you for putting your time into investing this.

hidapi (and python-hidapi) are the same version as yours.

I did try without using a USB hub but the core dump remains.

Apart from the log entry ( or systemd restarting the service because it things it failed) this seems to have however now implications on the functionality.

Unfortunately i haven't been able to test this in a clean install of my setup.

**Comment by dodgyrabbit** [comment]
No problem, this is a fascinating issue. Right now, I think it's an issue with the library we use - but I'm going to review the code and may open an issue if I have a clearer understanding. 

If this is a race condition - it's weird that it happens consistently on yours. Perhaps differences in CPU? What kind of CPU does your machine have? How many?

**Comment by dodgyrabbit** [comment]
@delpes A patch has been made in the streamdeck library.  Could you try it out? We'll have to wait for a new version to be published, but in the meantime you should be able to replace it locally and test drive it.

Here is a link to the python file called [LIbUSBHIDAPI.py](https://raw.githubusercontent.com/abcminiuser/python-elgato-streamdeck/9de5b623e623ddb683b5f000295d4b82263b864d/src/StreamDeck/Transport/LibUSBHIDAPI.py).

You should be able to locate this on your system with something like
``` console
find / -type f -name LibUSBHIDAPI.py 2>/dev/null
```

I suggest backing up the current on your machine and replacing it with the one linked above.

**Comment by delpes** [comment]
@dodgyrabbit 
Thank you very much. 
But it seems that this doesn't solve the problem:
```
api.py(168):             deck.close()
 --- modulename: StreamDeck, funcname: close
StreamDeck.py(159):         self.device.close()
 --- modulename: LibUSBHIDAPI, funcname: close
LibUSBHIDAPI.py(359):             with self.mutex:
LibUSBHIDAPI.py(360):                 if self.device_handle:
LibUSBHIDAPI.py(361):                     self.hidapi.close_device(self.device_handle)
 --- modulename: LibUSBHIDAPI, funcname: close_device
LibUSBHIDAPI.py(193):             if handle:
LibUSBHIDAPI.py(194):                 with self.mutex:
LibUSBHIDAPI.py(195):                     self.hidapi.hid_close(handle)
LibUSBHIDAPI.py(362):                     self.device_handle = None
api.py(165):     for _deck_serial, deck in decks.items():
gui.py(390):         sys.exit()
[1]    308929 segmentation fault (core dumped)  python3 -u -m trace -t
```

I double checked i'm on the right versions - which the code in the trace confirms.

About your cpu question:
Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz - 4 cores

**Comment by dodgyrabbit** [comment]
We should be open to the possibility that the segfault could be caused by something else.
I've installed manjaro 21 + bspwm and cannot reproduce.

Could you perhaps backup your `~/.streamdeck_ui.json` file, delete it and run streamdeck?
Then just click Exit. Does it still core dump?
Want to try eliminate Pillow or any other logic and see if it still crashes. That may narrow down the search.

**Comment by delpes** [comment]
I had more time to debug the issue and yes.
You are right. It is caused by something else:
Polybar.

Somehow their tray system (using XEMBED) seems to prevent streamdeck from shutting down orderly and provokes a segfault.

Sorry for the time wasted. I didn't think of the tray <-> application interaction and should have eliminated that variable right from the start.

I have to dig deeper into polybar and will fill an issue with them once i've got more details on how/why this happens.

Thanks again for your time!

**Comment by dodgyrabbit** [comment]
No problem @delpes glad you managed to figure it out. We did track down a couple of legit issues as a result of this, so in the end, all good.

If you want, you can make a pull request and add an item to the "known issues" in the README.md in case someone else runs into this problem.
