### ISSUE TITLE
Command does not work in Ubuntu 18.04.5 LTS (Bionic Beaver)

### ISSUE THREAD

**Issue by StubbsPKS** [timothycrosley/streamdeck-ui#113]
Putting anything into the Command spot that fails breaks streamdeck-ui.

Steps to reproduce:
1. Launch streamdeck either from CLI or from a Desktop launcher
2. Add `gnome-terminal` to the Command section for a button
3. Press that button on the streamdeck and watch the terminal open
4. Add `xdotool search --name '^Zoom Meeting$' windowactivate` to another button - I have tried this with a wrapper script, but that also breaks
5. Press that button on the streamdeck and it has no effect and now the terminal button it also broken
6. Restart `streamdeck-ui` to fix (this sometimes fixes it, but sometimes you need to unplug and replug the streamdeck)

* I have tried running streamdeck from a CLI to get output for debugging, but it didn't give me any output.
* The commands I have tried in the streamdeck work from the CLI

**Comment by tylerjw** [comment]
Can you try this:

```bash -c "xdotool search --name '^Zoom Meeting$' windowactivate"```

**Comment by StubbsPKS** [comment]
I had tried the full path to the tool, but didn't even think to do it with `bash -c`. I have good news and bad news.

**Good News**
My `streamdeck-ui` doesn't break when I hit a button that fails but is using `bash -c`. My other commands continue to work without needing to restart or unplugging and replugging the deck.

**Bad News**
I've also tried adding the full path like `bash -c "/usr/bin/xdotool search --name '^Zoom Meeting$' windowactivate"` but no luck.
I also tried `bash -c "wmctrl -a 'Zoom Meeting'"` which works in CLI but not in the button.

**Comment by tylerjw** [comment]
Hopefully someone with more gnome and/or python knowledge can help.  All I can say is that I use i3 (not sway) and have had generally good success controlling window manager functions (like changing focus) through the cli for i3 msg.

It defiantly is a bug that it silently fails.  You could look at the code that executes the command and try to instrument it to not crash or provide more useful debugging output.  The hack I suggested is to run your script in a subshell of bash, this helps protect the python script from getting in a bad state when that subshell goes bad, but obviously doesn't fix why it is going bad.

**Comment by StubbsPKS** [comment]
Thanks for the assist earlier, at least it's in a slightly better state now. For now I'm just using the `Press Keys` function to hit the keybinds for the functions I need, but I have to manually focus the window which isn't ideal when presenting.

I'll take a look at the code tonight after work, thanks again!

**Comment by tylerjw** [comment]
One idea I had from this, should we add a launchd script that can be enabled so this runs automatically in the background and sends output to some log file.  I'm not sure how that would interact with the the tray (can services started by systemd create gui windows later when you click on the tray icon?).  I imagine there might be some user-account type settings that we'd have to deal with.  I know that pulseaudio generally runs under your user account through systesmd.  Maybe we could do something similar?

**Comment by dodgyrabbit** [comment]
Interesting. I wonder if somehow pip has an outdated cache. I found [this](https://stackoverflow.com/a/17153977/192815).

You could also try setting the version explicitly
`pip3 install --user streamdeck-ui==1.0.7`

**Comment by desrod** [comment]
> I'm not sure how that would interact with the the tray

What "tray" are you speaking of? Which DE are you using? The solution has to be independent of DE, or solutions for multiple DEs should be provided. Not everyone runs Unity, or GNOME, or KDE or XFCE, etc.

**Comment by tylerjw** [comment]
> What "tray" are you speaking of? Which DE are you using? The solution has to be independent of DE, or solutions for multiple DEs should be provided. Not everyone runs Unity, or GNOME, or KDE or XFCE, etc.

Good point.  I'm currently on i3 (installed from apt on ubuntu 20.04) and I have to admit I don't know the details of how the tray was installed.  This application creates a small icon on the right of the status bar from i3 that minimizes/maximizes the application when clicked on.

**Comment by StubbsPKS** [comment]
I am on Ubuntu 18.04.5, maybe the repo **is** outdated for me

> pip3 install --user streamdeck-ui==1.0.7

```
user@LAPTOP-300635:~$ pip3 install --user streamdeck-ui==1.0.7
Collecting streamdeck-ui==1.0.7
  Could not find a version that satisfies the requirement streamdeck-ui==1.0.7 (from versions: 0.0.2, 0.0.3, 1.0.0, 1.0.1, 1.0.2)
No matching distribution found for streamdeck-ui==1.0.7
```

**Comment by tylerjw** [comment]
Try:

```
pip3 install --no-cache-dir --upgrade --user streamdeck-ui==1.0.7
```

**Comment by StubbsPKS** [comment]
Same error:
```Collecting streamdeck-ui==1.0.7
  Could not find a version that satisfies the requirement streamdeck-ui==1.0.7 (from versions: 0.0.2, 0.0.3, 1.0.0, 1.0.1, 1.0.2)
No matching distribution found for streamdeck-ui==1.0.7
```

**Comment by tylerjw** [comment]
I don't understand why that would happen, here it is in pypi: https://pypi.org/project/streamdeck-ui/

**Comment by StubbsPKS** [comment]
Well, looks like it's a case of needing to upgrade python. I was on python3.6 and needed python3.8. Updated to 3.8 and then installed `pythonlib3.8-dev` and now it all works fine, including the grabbing focus.

Thanks all for the assistance!

**Comment by tylerjw** [comment]
I don't understand python packaging, but maybe we need to release for older versions of python3 also (or explicitly state that this package works on older versions of python3, assuming it does)?

**Comment by StubbsPKS** [comment]
I noticed on pypi.org that it says: `Requires: Python >=3.8, <3.10` which is what gave me the idea to update python.

**Comment by dodgyrabbit** [comment]
I've updated the README with clearer instructions. https://github.com/timothycrosley/streamdeck-ui/commit/bdab3db092f2996491b55561e56d09fbbb57be04

> but maybe we need to release for older versions of python3 also (or explicitly state that this package works on older versions of python3, assuming it does)?

This is not possible since the underlying library we use requires Python 3.8. It is a bummer that pip does not provide any feedback that there is even the possibility of an upgrade.

Hopefully this helps the next person. Thanks all!
