### ISSUE TITLE
Installation on Ubuntu 18.04.5 LTS

### ISSUE THREAD

**Issue by capncrunch** [timothycrosley/streamdeck-ui#116]
I've successfully installed streakdeck-ui on Ubuntu 18.04.5 LTS but needed a couple additional steps:

For hidapi to build successfully, I needed to install the package `libudev-dev` in addition to the packages to be installed as outlined in the documentation.

In addition, as outlined in #113, Ubuntu's system default for python3 in 18.04.5 LTS is python 3.6. Ubuntu does, however, provide python 3.8 packages, so I installed the packages `python3.8 python3.8-dev` as well.

Unfortunately, Ubuntu does not offer a pip3.8 package, so this needed to be installed from pip

`python3.8 -m pip install pip`

With $HOME/.local/bin added to my PATH, I could then run `pip3.8 install --user streamdeck-ui`

May I suggest adding this to the documentation and Ubuntu script?

**Comment by dodgyrabbit** [comment]
Thanks for the feedback. I've given this a run through myself on an Ubuntu 18.04 VM and took note of the process.
Added a doc and linked to it from the main readme.

If you could take a look that would be great. 

Note that I did not have to install libudev-dev. Only python3.8-dev was required for a successful install.

https://github.com/timothycrosley/streamdeck-ui/blob/master/docs/ubuntu1804.md

**Comment by capncrunch** [comment]
The libudev-dev requirement might have come from my first installation attempt using python6.3. The package needing this (hidapi) does not appear to be pulled in for the python6.8 install.

The guide looks fine to me, only change I would make is setting the PATH where I would add the local path at the end rather then in the front so as not to accidentally override system commands. This is also, to a lesser extent, a security measure.

**Comment by capncrunch** [comment]
I've now also tested this further by uninstalling all pip packages as well as the libudev-dev package and then reinstalling streamdeck-ui and it did not need libudev-dev at all. So I can now confirm your results.

With regards to the PATH, upon further investigation, it is **necessary** to have the local path last as pip3.8 also installs a pip and pip3 variant which would then override the system default pip2 and pip3.6, respectively.

**Comment by dodgyrabbit** [comment]
Thanks @capncrunch I've updated the guide.
