### ISSUE TITLE
Cannot reopen main window once closed

### ISSUE THREAD

**Issue by capncrunch** [timothycrosley/streamdeck-ui#117]
When closing the main (settings) window, streamdeck-ui continues to run in the tray. This is by design and great.

However, there currently doesn't seem to be a way to reopen the main window without stopping and restarting streamdeck-ui. The tray icon's only option is Exit and double clicking does nothing.

I might be daft here (in which case I would like to ask for a line in the manual) but if not I'd like to suggest an Open Main Window option for the tray icon.

**Comment by dodgyrabbit** [comment]
You should be able to double click the icon in the tray, to bring the settings window back.

However, I agree that having a menu item makes sense. In fact, in another branch I've been working on, I did exactly that.

**Comment by capncrunch** [comment]
In my environment (Xubuntu 18.04.5 LTS), clicking the tray icon opens the icon menu, double clicking the tray icons does so very fast. :-)

This seems to be true for all tray icons here, I've never noticed before.

Most likely an Xfce issue, then.

**Comment by tylerjw** [comment]
I'm on i3 and clicking on the tray icon brings it back.  I don't like clicking on things so I just have it start on the 10th workspace when I log in (where I "background" applications I want to run that have UI elements I might want to access).

**Comment by dodgyrabbit** [comment]
Take a look at v1.1.1
As always, your feedback appreciated before it's published.

**Comment by capncrunch** [comment]
I have tested v1.1.1 and it works fine for me and resolves this issue.

**Comment by keilmillerjr** [comment]
I am running gnome 43.4. There is no system tray support. Once you start and then close the app, you can't reopen it. I had to download the extension appindicator-support.

https://extensions.gnome.org/extension/615/appindicator-support/
