### ISSUE TITLE
New version to test 1.1.1

### ISSUE THREAD

**Issue by dodgyrabbit** [timothycrosley/streamdeck-ui#118]
I've published a **test version [1.1.1](https://test.pypi.org/project/streamdeck-ui/)** on test.pypi.org for those of you interested to give it a run and provide feedback before it is published on the main repository.

### How to upgrade

Uninstall your current version
``` console
$ pip3 uninstall streamdeck-ui 
```
Install the latest version from the **test.pypi.org** server.
``` console
$ pip3 install -i https://test.pypi.org/simple/ streamdeck-ui==1.1.1 --user
```
### How to downgrade
Remove the test version
```
$ pip3 uninstall streamdeck-ui
```
Install the latest from the **main** repository. 
``` console
$ pip3 install streamdeck-ui --user
```
If you are running into issues, please open a separate issue and provide as much detail as possible. Steps you took, output, your operating system version, streamdeck version, screenshots - whatever can help. Thanks!

### What's new?
* If you want to immediately dim the display, the context menu on the tray allows for that. Click it again toggles the display back on.
* Configure will show the main window. Useful for xfce and other window managers where the tray click functionality is not working well.
![image](https://user-images.githubusercontent.com/518187/115648679-ddfc8a80-a2f3-11eb-8a91-5009adced579.png)

**Comment by capncrunch** [comment]
I have tested this version and it works fine for me.
