### ISSUE TITLE
'Key' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by DNEAVES** [timothycrosley/streamdeck-ui#119]
I'm getting this error when trying to use any non-single-letter in the "Press Key" field. So examples of keys I've tried are "cmd" (Super, on Linux), "ctrl", any "F#" keys. I get the following error:

```
Traceback (most recent call last):
  File "/home/dneaves/.local/lib/python3.8/site-packages/streamdeck_ui/gui.py", line 243, in handle_keypress
    if key_name.startswith("delay"):
AttributeError: 'Key' object has no attribute 'startswith'
```
Despite the error message, I'm not actually trying to use the "delay" feature, that's just where the line of code that produces the error starts. If I do use the "delay" special character (followed by any single-letter keys), there are no issues.

I suspect this issue comes from lines 238-239 of /streamdeck_ui/gui.py , as it has just converted any modifier keys or non-letter keys denoted by pynput from strings to enums. This would make any of these keys not follow the string method .startswith()

A quick example of this from the python console:

```
>>> from enum import Enum

>>> class TestEnum(Enum):
...    testcase = 1

>>> enumobj = TestEnum.testcase

>>> enumobj.startswith('testcase')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'TestEnum' object has no attribute 'startswith'

```

However, adding a .name method to an enum will return the original name, so perhaps this will lead to the solution? `enumobj.name.startswith('testcase')` results as True, so that would fix the enum problem, but may lead to errors with the strings. so perhaps at line 243 we begin with a type-check (pseudo-code: if type = enum, do thing 1, elif type = str do thing 2?) to see if its an enum or a string, then do then proceed from there?

I'm assuming I'm using the most recent version of streamdeck-ui, as I just installed it this afternoon.

**Comment by dodgyrabbit** [comment]
Thanks for reporting this. Managed to reproduce and you are correct, it's a regression. Will fix it.

**Comment by dodgyrabbit** [comment]
Version 1.1.2 has been published and should resolve your issue.
Could you please confirm

**Comment by DNEAVES** [comment]
Now I can use most of the "Special" keys, with the exceptions of F13-F20, [despite it being listed on pynput](https://pynput.readthedocs.io/en/latest/_modules/pynput/keyboard/_base.html#Key). When run from a terminal it says (For key F13):
```
Could not press key 'Key.f13'
Could not release key 'Key.f13'
```

Not sure if this is an error of streamdeck-ui, or an issue stemming from pynput (since pyinput.keyboard imported Key), or perhaps its just my distro, as F13-24 don't show on `xmodmap -pke`, so how do you press a key that doesn't exist.

So this issue is technically fixed, yes. Thanks for the quick resolution!
