### ISSUE TITLE
Unable to install on Linux Mint 19.2

### ISSUE THREAD

**Issue by rbplayslinux** [timothycrosley/streamdeck-ui#12]
I am not a programmer by any means and am looking for suggestions on how to remedy the issue. When I try to install streamdeck-ui on my Mint 19.2 laptop I receive this:

rb@rb-ThinkPad-T420:~$ pip3 install streamdeck_ui --user
Collecting streamdeck_ui
  Downloading https://files.pythonhosted.org/packages/f0/d0/8349e057e9c02fcf3b2a6cfe2c1e4c3b4cafb813704879eda9e5810ffecf/streamdeck_ui-1.0.1-py3-none-any.whl (1.2MB)
    100% |████████████████████████████████| 1.2MB 1.2MB/s 
Collecting pynput<2.0,>=1.4 (from streamdeck_ui)
  Downloading https://files.pythonhosted.org/packages/00/46/b1b4a915c1ca423eb8cc5640f2c1dfa2eaf6a08c450831fdce68886f4b0c/pynput-1.4.5-py2.py3-none-any.whl (83kB)
    100% |████████████████████████████████| 92kB 7.8MB/s 
Collecting streamdeck<0.6.0,>=0.5.0 (from streamdeck_ui)
  Downloading https://files.pythonhosted.org/packages/df/21/58327a722cfb1a17fd74fe7409d0beb085aebb95f79966dd926ea9fada2d/streamdeck-0.5.1-py3-none-any.whl
Collecting pillow<7.0,>=6.1 (from streamdeck_ui)
  Downloading https://files.pythonhosted.org/packages/10/5c/0e94e689de2476c4c5e644a3bd223a1c1b9e2bdb7c510191750be74fa786/Pillow-6.2.1-cp36-cp36m-manylinux1_x86_64.whl (2.1MB)
    100% |████████████████████████████████| 2.1MB 609kB/s 
Collecting pyside2<6.0,>=5.13 (from streamdeck_ui)
  Downloading https://files.pythonhosted.org/packages/ea/58/e5a1aa7417f87987f03f02c0d0ce4bb1112ae9981667107ee9a1560f3607/PySide2-5.13.2-5.13.2-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl (156.1MB)
    100% |████████████████████████████████| 156.1MB 9.4kB/s 
Collecting hidapi<0.8.0,>=0.7.99 (from streamdeck_ui)
  Downloading https://files.pythonhosted.org/packages/c1/86/89df0e8890f96eeb5fb68d4ccb14cb38e2c2d2cfd7601ba972206acd9015/hidapi-0.7.99.post21.tar.gz (51kB)
    100% |████████████████████████████████| 61kB 6.4MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rxlawfug/hidapi/

**Comment by xorbital** [comment]
Does
```bash
sudo apt install python3-setuptools
```
fix it?

**Comment by rbplayslinux** [comment]
Didn't solve the issue but I did get a little farther. Here is what I get now:

rb@rb-Bonobo-Extreme:/etc/udev/rules.d$ pip3 install --user streamdeck_ui
Collecting streamdeck_ui
  Using cached https://files.pythonhosted.org/packages/98/4d/fe60feaa7b0d5c7afac6da68cfb8b4fd5f48a10e3f9824e3764e7301a5a4/streamdeck_ui-1.0.2-py3-none-any.whl
Collecting pillow<7.0,>=6.1 (from streamdeck_ui)
  Downloading https://files.pythonhosted.org/packages/10/5c/0e94e689de2476c4c5e644a3bd223a1c1b9e2bdb7c510191750be74fa786/Pillow-6.2.1-cp36-cp36m-manylinux1_x86_64.whl (2.1MB)
    100% |████████████████████████████████| 2.1MB 803kB/s 
Collecting pyside2<6.0,>=5.13 (from streamdeck_ui)
  Using cached https://files.pythonhosted.org/packages/74/f7/738a55a81eebb854c263622822e551bcff4276b96b5a8eadfed12500ee46/PySide2-5.14.0-5.14.0-cp35.cp36.cp37.cp38-abi3-manylinux1_x86_64.whl
Collecting hidapi<0.8.0,>=0.7.99 (from streamdeck_ui)
  Using cached https://files.pythonhosted.org/packages/c1/86/89df0e8890f96eeb5fb68d4ccb14cb38e2c2d2cfd7601ba972206acd9015/hidapi-0.7.99.post21.tar.gz
Collecting streamdeck<0.7.0,>=0.6.3 (from streamdeck_ui)
  Using cached https://files.pythonhosted.org/packages/3c/6a/ac634488e03aceb537ed8b491a180498ab75e2ce6f37a75dc2e042678b51/streamdeck-0.6.3-py3-none-any.whl
Collecting pynput<2.0,>=1.4 (from streamdeck_ui)
  Using cached https://files.pythonhosted.org/packages/43/c9/cfeb5d35c4b8ef34817b2cf865fa7d13d7df688e4db73024a83048767684/pynput-1.6.3-py2.py3-none-any.whl
Collecting shiboken2==5.14.0 (from pyside2<6.0,>=5.13->streamdeck_ui)
  Downloading https://files.pythonhosted.org/packages/d2/ed/95ed9353202b3e4115373288a7517fe0a13d70755fcb599d2df399ed9f4a/shiboken2-5.14.0-5.14.0-cp35.cp36.cp37.cp38-abi3-manylinux1_x86_64.whl (848kB)
    100% |████████████████████████████████| 849kB 1.9MB/s 
Collecting setuptools>=19.0 (from hidapi<0.8.0,>=0.7.99->streamdeck_ui)
  Downloading https://files.pythonhosted.org/packages/54/28/c45d8b54c1339f9644b87663945e54a8503cfef59cf0f65b3ff5dd17cf64/setuptools-42.0.2-py2.py3-none-any.whl (583kB)
    100% |████████████████████████████████| 583kB 2.9MB/s 
Collecting six (from pynput<2.0,>=1.4->streamdeck_ui)
  Downloading https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting python-xlib>=0.17; "linux" in sys_platform (from pynput<2.0,>=1.4->streamdeck_ui)
  Downloading https://files.pythonhosted.org/packages/ca/37/1e6d9cd3454a25d5d6a72c8528d4c9cde2b2252a9628aefeec083c58184c/python_xlib-0.26-py2.py3-none-any.whl (174kB)
    100% |████████████████████████████████| 184kB 5.9MB/s 
Building wheels for collected packages: hidapi
  Running setup.py bdist_wheel for hidapi ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-q1rlzogm/hidapi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp0qolnd6fpip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for hidapi
  Running setup.py clean for hidapi
Failed to build hidapi
Installing collected packages: pillow, shiboken2, pyside2, setuptools, hidapi, streamdeck, six, python-xlib, pynput, streamdeck-ui
  Running setup.py install for hidapi ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-q1rlzogm/hidapi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-t6p76rfd-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    WARNING: The wheel package is not available.
    running install
    running build
    running build_ext
    cythoning hid.pyx to hid.c
    /tmp/pip-build-q1rlzogm/hidapi/.eggs/Cython-0.29.14-py3.6-linux-x86_64.egg/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-build-q1rlzogm/hidapi/hid.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    cythoning hidraw.pyx to hidraw.c
    /tmp/pip-build-q1rlzogm/hidapi/.eggs/Cython-0.29.14-py3.6-linux-x86_64.egg/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-build-q1rlzogm/hidapi/hidraw.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    building 'hid' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/hidapi
    creating build/temp.linux-x86_64-3.6/hidapi/libusb
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Ihidapi/hidapi -I/usr/include/libusb-1.0 -I/usr/include/python3.6m -c hid.c -o build/temp.linux-x86_64-3.6/hid.o
    hid.c:4:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-q1rlzogm/hidapi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-t6p76rfd-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-q1rlzogm/hidapi/

**Comment by louhy** [comment]
Try this: 
sudo apt-get install python3-dev

**Comment by dodgyrabbit** [comment]
Original issue opened 2 years ago. Closing for now.

**Comment by TylerCode** [comment]
Hello, wasn't sure if creating a new issue was better or commenting here. I'm getting the same issue today on ZorinOS 15. 

```
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for hidapi
  Running setup.py clean for hidapi
Failed to build hidapi
Installing collected packages: setuptools, hidapi, pillow, shiboken2, pyside2, streamdeck, six, python-xlib, evdev, pynput, streamdeck-ui
  Running setup.py install for hidapi ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-fdmhhy5j/hidapi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-9ae7_rsc-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_ext
    skipping 'hid.c' Cython extension (up-to-date)
    skipping 'hidraw.c' Cython extension (up-to-date)
    building 'hid' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/hidapi
    creating build/temp.linux-x86_64-3.6/hidapi/libusb
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Ihidapi/hidapi -I/usr/include/libusb-1.0 -I/usr/include/python3.6m -c hid.c -o build/temp.linux-x86_64-3.6/hid.o
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Ihidapi/hidapi -I/usr/include/libusb-1.0 -I/usr/include/python3.6m -c hidapi/libusb/hid.c -o build/temp.linux-x86_64-3.6/hidapi/libusb/hid.o
    hidapi/libusb/hid.c:47:10: fatal error: libusb.h: No such file or directory
     #include <libusb.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-fdmhhy5j/hidapi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-9ae7_rsc-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-fdmhhy5j/hidapi/
```

**Comment by louhy** [comment]
@TylerCode IMO you should open a new issue since this is closed, and might not be seen by many people.
