### ISSUE TITLE
Drag and drop icons?

### ISSUE THREAD

**Issue by ScuttleSE** [timothycrosley/streamdeck-ui#122]
Am I supposed to be able to drag and drop icons on the UI? Whenever I do I get the below error:

```
Traceback (most recent call last):
  File "/home/scuttle/.local/lib/python3.9/site-packages/streamdeck_ui/gui.py", line 177, in dropEvent
    if e.source().index == self.index:
AttributeError: 'NoneType' object has no attribute 'index'

```

**Comment by dodgyrabbit** [comment]
No, this is not a supported feature. However, a [PR](https://github.com/timothycrosley/streamdeck-ui/pull/121) has been created, which will provide this feature once merged.

You can move buttons around using drag/drop.

**Comment by ScuttleSE** [comment]
Gotcha!
