### ISSUE TITLE
Button press not registered (or not firing action)

### ISSUE THREAD

**Issue by ilons** [timothycrosley/streamdeck-ui#131]
First of all, great work with streamdeck-ui!

Python 3.8.6
streamdeck==0.8.4
streamdeck-ui==1.1.2

I have an issue that when I press a button, sometimes the associated action will now fire.
Usually, it works by first pressing some other button, and then the first one again.

Is there any way to turn on verbose output to debug this?

**Comment by ilons** [comment]
Looking at when `_key_change_callback` is called, it is never called more than once when pressing the same button.

So, when I press button 0, it gets called with True, and next time I press 0 it does not get called.
If I press button 0, then 1, then 0, it gets called as:
0, True
0, False
1, True
0, True

This in effect means that the same button cant be pressed twice (and have an effect).

Is this intentional? Given the description of the function it seems not.
1, False

**Comment by dodgyrabbit** [comment]
This does not sound correct. The callback is invoked by the streamdeck library, which in turn polls the device at 20Hz.  Just for posterity, the implementation is [here](https://github.com/abcminiuser/python-elgato-streamdeck/blob/2786a795a05b441d1271e694b6b3c8e7871060b1/src/StreamDeck/Devices/StreamDeck.py#L101).

Could you provide some more information please?

- What operating system/version do you use?
- What Stream Deck model are you using? [How to find out](https://help.elgato.com/hc/en-us/articles/360052737551-Finding-Serial-and-Model-Numbers-of-Elgato-Devices)
- Does this behaviour happen independent of what action you choose (i.e. key press vs command vs change page)?

**Comment by ilons** [comment]
OS: Linux
distribution: Pop! OS 21.04
Kernel: 5.11.0-7620
StreamDeck: 20GAT9901

Running a single StreamDeck.

You are correct that it seems to be something in my setup. I tried a different USB-port (on my laptop instead of the USB-C dock), which fires the event on each key press.
I then switched port on the USB dock (unplugging another device), and it yet again fired the events.
I the re-plugged the unplugged device, in a port I originally used for my StreamDeck, **and it no longer fires every event.**
Then I unplugged ANOTHER device from the dock, AND changed the port for the StreamDeck, which still only fired one event on multiple presses of the same key.

Both devices on dock, does not work.
Other device unplugged and StreamDeck on dock works.
Plugging in both the devices directly to the laptop works.
StreamDeck on dock and the other device on the computer works.

To sum it up, when having it connected to my USB-dock, with another specific device connected at the same time, to the same dock, it fires the events only once.

I don't really know how to debug this further. It shouldn't be a problem with the bandwidth from the dock (as it is connected over USB-C).

Here is a list of my connected USB devices:
```
Bus 005 Device 005: ID 046d:c069 Logitech, Inc. M-U0007 [Corded Mouse M500]
Bus 005 Device 004: ID 046d:c318 Logitech, Inc. Illuminated Keyboard
Bus 005 Device 029: ID 0fd9:006c Elgato Systems GmbH Stream Deck XL
Bus 005 Device 031: ID 19f7:0003 RODE Microphones RODE NT-USB
Bus 005 Device 030: ID 046d:082d Logitech, Inc. HD Pro Webcam C920
```
The device that makes StreamDeck stop registering key presses is the Røde Microphone.
The dock itself is a Lenovo Thunderbolt 3 Dock.

**Comment by dodgyrabbit** [comment]
From what you describe, it sounds to me like a hardware problem, not a software one.
Some time ago, another user observed similar behaviour:
https://github.com/timothycrosley/streamdeck-ui/issues/69#issuecomment-715887397

On the Elgato website they reveal some information:
https://help.elgato.com/hc/en-us/articles/360028233331-Elgato-Stream-Deck-Using-USB-Cable-Extensions

I can only imagine that the combined current draw from the Stream Deck XL and the RODE Microphone causes a problem for the micro on the Stream Deck.

One thought I had - try lowering the brightness on the StreamDeck. Depending on the technology they use, this may limit the current draw - presumably each key has an individual LED backlight. On the XL that may give enough breathing room for it to work properly.

**Comment by ilons** [comment]
I agree, this probably has nothing to do with streamdeck-ui itself, but either hardware or other software. Thank you for spending the time and answering the issue!
