### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by jolinux** [timothycrosley/streamdeck-ui#134]
Hello,

this error crashed if I  start streamdesk.

My OS is Debian 10 Buster. I install python3.8  without DEbian-System, because Buster has no 3.8.  And do all steps from readme.md  and install streamdesk_ui  (pip3.8 install streamdeck-ui --user)

The Error:
qt.qpa.plugin: Could not load the Qt platform plugin "xcb"

is a problem from QT but I found no solution for Debian 10 Buster.

This is the Output from Xterm/Konsole 

Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/usr/local/bin/platforms" ...
Cannot load library /home/jo/.local/lib/python3.8/site-packages/PySide2/Qt/plugins/platforms/libqxcb.so: (libxcb-util.so.1: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden)
QLibraryPrivate::loadPlugin failed on "/home/jo/.local/lib/python3.8/site-packages/PySide2/Qt/plugins/platforms/libqxcb.so" : "Cannot load library /home/jo/.local/lib/python3.8/site-packages/PySide2/Qt/plugins/platforms/libqxcb.so: (libxcb-util.so.1: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Abgebrochen

I dont't know  why this loading-Error because the file

 /home/jo/.local/lib/python3.8/site-packages/PySide2/Qt/plugins/platforms/libqxcb.so  

exists

Before I do 
export QT_DEBUG_PLUGINS=1
( a TIp from internet)

**Comment by jolinux** [comment]
Hello, thanks for answer.  #51    But

I do
sudo apt install --reinstall libxcb-xinerama0

Error is the same

I download the script (copy/paste) start the script as sudo and user . Script install something or not (because the system has the files before installed)

The print
############################################
echo 'Installing libraries'
Installing libraries

    sudo apt install qt5-default libhidapi-hidraw0 libudev-dev libusb-1.0-0-dev python3-pip
    Paketlisten werden gelesen... Fertig
    Abhängigkeitsbaum wird aufgebaut.
    Statusinformationen werden eingelesen.... Fertig
    libhidapi-hidraw0 ist schon die neueste Version (0.8.0rc1+git20140818.d17db57+dfsg-2).
    libusb-1.0-0-dev ist schon die neueste Version (2:1.0.22-2).
    python3-pip ist schon die neueste Version (18.1-5).
    qt5-default ist schon die neueste Version (5.11.3+dfsg1-1+deb10u4).
    libudev-dev ist schon die neueste Version (241-7deb10u7).
    Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
    gir1.2-keybinder-3.0 libkeybinder-3.0-0 python-glade2 python-gst-1.0
    Verwenden Sie »sudo apt autoremove«, um sie zu entfernen.
    0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
    echo 'Adding udev rules and reloading'
    Adding udev rules and reloading
    ++ whoami
    sudo usermod -a -G plugdev jo
    sudo tee /etc/udev/rules.d/99-streamdeck.rules
    SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", MODE:="666", GROUP="plugdev"
    SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0063", MODE:="666", GROUP="plugdev"
    SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006c", MODE:="666", GROUP="plugdev"
    SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006d", MODE:="666", GROUP="plugdev"
    sudo udevadm control --reload-rules
    echo 'Unplug and replug in device for the new udev rules to take effect'
    Unplug and replug in device for the new udev rules to take effect
    echo 'Installing streamdeck_ui'
    Installing streamdeck_ui
    pip3 install --user streamdeck_ui
    Requirement already satisfied: streamdeck_ui in ./.local/lib/python3.8/site-packages (1.1.2)
    Requirement already satisfied: pyside2<6.0,>=5.13 in ./.local/lib/python3.8/site-packages (from streamdeck_ui) (5.15.2)
    Requirement already satisfied: streamdeck<0.9.0,>=0.8.4 in ./.local/lib/python3.8/site-packages (from streamdeck_ui) (0.8.4)
    Requirement already satisfied: pillow<9.0,>=8.2 in ./.local/lib/python3.8/site-packages (from streamdeck_ui) (8.2.0)
    Requirement already satisfied: pynput<2.0,>=1.7 in ./.local/lib/python3.8/site-packages (from streamdeck_ui) (1.7.3)
    Requirement already satisfied: python3-xlib<0.16,>=0.15 in ./.local/lib/python3.8/site-packages (from streamdeck_ui) (0.15)
    Requirement already satisfied: evdev>=1.3 in ./.local/lib/python3.8/site-packages (from pynput<2.0,>=1.7->streamdeck_ui) (1.4.0)
    Requirement already satisfied: six in ./.local/lib/python3.8/site-packages (from pynput<2.0,>=1.7->streamdeck_ui) (1.16.0)
    Requirement already satisfied: python-xlib>=0.17 in ./.local/lib/python3.8/site-packages (from pynput<2.0,>=1.7->streamdeck_ui) (0.30)
    Requirement already satisfied: shiboken2==5.15.2 in ./.local/lib/python3.8/site-packages (from pyside2<6.0,>=5.13->streamdeck_ui) (5.15.2)
    WARNING: You are using pip version 20.3.4; however, version 21.1.2 is available.
    You should consider upgrading via the '/usr/local/bin/python3.8 -m pip install --upgrade pip' command.
    echo 'If the installation was successful, run '''streamdeck''' to start.'
    If the installation was successful, run 'streamdeck' to start.
    #######################################################################

Error is the same. Debian 10 Buster is not Ubuntu -)) No idea to fix a Debian system ??

Which lib is the problem ?

Hope a user has a solution

**Comment by jolinux** [comment]
Found a solution for Debain 10 Buster

Problem is Lib   libqxcb.so  .   Found after install python3.8 in local user path

 /home/jo/.local/lib/python3.8/site-packages/PySide2/Qt/plugins/platforms/libqxcb.so

If you ask 
ldd  /home/jo/.local/lib/python3.8/site-packages/PySide2/Qt/plugins/platforms/libqxcb.so

lib 
libxcb-util.so  is not install. 

A new symbol-link   is the solution 

/usr/lib/x86_64-linux-gnu$ sudo ln -s libxcb-util.so.0.0.0 libxcb-util.so.1



see here
https://forum.qt.io/topic/93247/qt-qpa-plugin-could-not-load-the-qt-platform-plugin-xcb-in-even-though-it-was-found/81

**Comment by deepy** [comment]
If anyone else ends up here with this issue then `apt install libxcb-icccm4 libxcb-render-util0 libxcb-keysyms1` may fix it

If you run the application as `QT_DEBUG_PLUGINS=1 ~/.local/bin/streamdeck` you'll see something like:

```Cannot load library /home/deepy/.local/lib/python3.9/site-packages/PySide2/Qt/plugins/platforms/libqxcb.so: (libxcb-icccm.so.4: cannot open shared object file: No such file or directory)```

You can run `ldd` against this file and check what's reported as `not found` and just install those

**Comment by CrikersPL** [comment]
`flatpak override --user --env=QT_QPA_PLATFORM=wayland org.kde.dolphin`
(org.kde.dolphin) in my case

Worked for me

**Comment by brentpicasso** [comment]
If anyone is still having problems, this may help: 

```
sudo apt-get install libxcb-cursor0
```
