### ISSUE TITLE
Start to tray 'streamdeck -n' on Acrolinux

### ISSUE THREAD

**Issue by Data-007** [timothycrosley/streamdeck-ui#140]
Hi
The issue is on arch(Arcolinux) the start to tray function simply does not work.
It would be nice to although a non Gui start as per documentation streamdeck -n
thanks

**Comment by FrankyB** [comment]
I think this is more kind of a race condition - assuming you are running kde.
I've got the issue when autostarting streamdeck -n on login. Then the UI is shown. If started via terminal when kde is running the ui is not shown but the tray icon. So I assume the systray is not loaded/started/ready when autostarting streamdeck. Maybe there is some expertise on how to wait until systray is available, then minimize to it.

**Comment by dodgyrabbit** [comment]
Could someone elaborate what the issue is here exactly, steps to reproduce, screenshots etc
It's not clear what the problem is. Please reopen the issue if you are able to provide more details. Not familiar with all the distros, so please do provide as much info as possible.
