### ISSUE TITLE
Breaks cinnamon settings on Linux Mint 20.2 Uma

### ISSUE THREAD

**Issue by chimpdev2** [timothycrosley/streamdeck-ui#145]
Hello, I have found an issue with streamdeck-ui as where it breaks the settings menu on Linux Mint 20.2 Uma using cinnamon. After installation, whenever you open cinnamon-settings in the terminal it just gives the error "Segmentation Fault (core dumped)" I narrowed it down to it to this app specifically because after a fresh installation, and installing streamdeck-ui it gives the error. Hope it gets fixed.

**Comment by chimpdev2** [comment]
issue solved, pillow was causing the issue with settings and isnt required

**Comment by YalithKBK** [comment]
Can you explain a little more on this? I was in the same boat (fresh install Linux 20 cinnamon, things broke after installing steamdeck). I poked around on the internet searching for a solution to my system settings not opening and someone suggested installing Pillow-2.7.0, so I did. This uninstalled the much later Pillow-8.3.1 that was installed with steamdeck.

It seems to have fixed my issue with various Linux things not showing up (system settings, etc) but now steamdeck won't run. So when you say Pillow isn't required, what do you mean? Reverting back to an earlier version seems to have broken the program for me.
