### ISSUE TITLE
Start minimized to the menu

### ISSUE THREAD

**Issue by fire** [timothycrosley/streamdeck-ui#146]
Wanted to suggest a new UIUX suggestion.

I want to the ability for streamdeck-ui to automatically startup minimized.

**Comment by iotku** [comment]
I believe the `-n` flag does what you're looking for an spawns streamdeck-ui directly into the system tray.

**Comment by fire** [comment]
Thanks.

**Comment by jlimas** [comment]
lol I have been waiting for this feature without looking at the closed issues, this is perfect!
