### ISSUE TITLE
Add the ability to rearrange the buttons.

### ISSUE THREAD

**Issue by fire** [timothycrosley/streamdeck-ui#15]
Add the ability to rearrange the buttons. This was noticeably absent.

**Comment by dodgyrabbit** [comment]
FYI I implemented this in a [fork](https://github.com/dodgyrabbit/streamdeck-ui).

**Comment by dodgyrabbit** [comment]
This feature has been merged.
44265b12a7ccbf201176766ea7e63d2a3e5c1122
