### ISSUE TITLE
Add option to start streamdeck service only and add how-to to readme.md

### ISSUE THREAD

**Issue by PropFault** [timothycrosley/streamdeck-ui#153]
Currently, the readme only states that 'It's recommended that you include streamdeck in your windowing environment's list of applications to auto-start.'.

The issue is that, currently when adding the streamdeck command to your startup options, it causes the entire GUI to open every time you log in. This is undesirable, since a streamdeck is not commonly reconfigured every time the user logs in. Therefore, it would be useful to be able to only start the background service so that the streamdeck is useable without opening the GUI every time. 

Regardless of weather or not this feature is already available, a line that states the command/command options to do this should be added to the readme.md. I understand that it may be possible to find this information by searching through the source, however, I think this is something that someone may want to do often enough that adding it to the readme.md is justified. Adding the command to just start the service right under the 'It's recommended that you include streamdeck in your windowing environment's list of applications to auto-start.' - line would suffice in my opinion.

**Comment by Data-007** [comment]
streamdeck -n

Although this douse not seem to work, see my thread here on this github. A list off  switches is available 

streamdeck -h

in both cases this is launched from the prompt in linux, but I would imagine winblows would be similar

**Comment by dodgyrabbit** [comment]
Thanks for the suggestion. Updated in https://github.com/timothycrosley/streamdeck-ui/commit/39dc9f0e031d22c6c334bb5ac7030dfb2c8e68f2
