### ISSUE TITLE
Streamdeck-ui has problems handling 2 streamdecks connected simultaneously.

### ISSUE THREAD

**Issue by flajann2** [timothycrosley/streamdeck-ui#156]
I have the 8x4 and the 5x3 streamdecks connected, and Streamdeck-ui behaves in a very flaky manner when I try to set them up.

Sometimes, the decks don't sync properly. Display of the icons are a bit wonky.

I know this is not exactly a precise bug report, but then you can try this for yourself and see what happens. I can provide more details later when I have time.

System:

OS: Arch Linux x86_64
Kernel: 5.13.12-arch1-1
Uptime: 1 day, 19 hours, 40 mins
Packages: 1592 (pacman), 13 (flatpak)
Shell: bash 5.1.8
Resolution: 1440x2560, 1440x2560, 3840x2160
DE: Plasma 5.22.4
WM: KWin
WM Theme: QTStepGradientRC319p
Theme: ArchSmooth [Plasma], Breeze [GTK2/3]
Icons: [Plasma], Tela [GTK2/3]
Terminal: tmux
CPU: AMD Ryzen Threadripper 3970X (64) @ 3.700GHz
GPU: NVIDIA GeForce RTX 3080 Ti
Memory: 104553MiB / 257591MiB

**Comment by dodgyrabbit** [comment]
Hi, unfortunately I don't have multiple streamdecks to try it out - but perhaps you can share some more information about what actually happens.

> Sometimes, the decks don't sync properly.
Can you elaborate what you mean with "don't sync properly"?

>  Display of the icons are a bit wonky.
Could you take a picture of what you are seeing and post it here?

> I can provide more details later when I have time.
That would be much appreciated.

If you only attach one Stream Deck at a time - does it work correctly?

**Comment by flajann2** [comment]
One streamdeck connected works nicely.
If you've never tested with 2 or more, that explains it.
I'll see when I can get a break so I can help you debug this.

**Comment by flajann2** [comment]
I failed to mention that I have 2 differently-sized Steamdecks.  The 8x4 one and the one the 5x3 one.
Let me try it again when I get the chance.

**Comment by dodgyrabbit** [comment]
There are problems with having two Stream Decks connected in the currently released version. There will be a version to try out soon - please keep an eye out. Would appreciate it if you could try it out and help identify issues.

**Comment by dodgyrabbit** [comment]
@flajann2 could you try version 2.0.1 and let us know? See issue #206

**Comment by dodgyrabbit** [comment]
Closing this, as confirmed the latest version is working in #221
