### ISSUE TITLE
pip installing streamdeck-ui fails on Pop!_OS 21.04

### ISSUE THREAD

**Issue by riccardoerra** [timothycrosley/streamdeck-ui#157]
Followed the manual installation steps and did:
`sudo apt install python3-pip libhidapi-libusb0 libxcb-xinerama0`
then `sudoedit /etc/udev/rules.d/70-streamdeck.rules`
edited the file with
```
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0063", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006c", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006d", TAG+="uaccess"
```
reloaded with `sudo udevadm control --reload-rules`
but then when I do `pip3 install streamdeck-ui --user` I get:
```
Collecting streamdeck-ui
  Using cached streamdeck_ui-1.1.2-py3-none-any.whl (1.2 MB)
Collecting python3-xlib<0.16,>=0.15
  Using cached python3_xlib-0.15-py3-none-any.whl
Requirement already satisfied: streamdeck<0.9.0,>=0.8.4 in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (from streamdeck-ui) (0.8.5)
Collecting pyside2<6.0,>=5.13
  Using cached PySide2-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-abi3-manylinux1_x86_64.whl (164.3 MB)
Collecting pillow<9.0,>=8.2
  Using cached Pillow-8.3.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (3.0 MB)
Collecting pynput<2.0,>=1.7
  Using cached pynput-1.7.3-py2.py3-none-any.whl (99 kB)
Collecting evdev>=1.3
  Using cached evdev-1.4.0.tar.gz (26 kB)
Requirement already satisfied: six in ./.local/lib/python3.9/site-packages (from pynput<2.0,>=1.7->streamdeck-ui) (1.16.0)
Requirement already satisfied: python-xlib>=0.17 in ./.local/lib/python3.9/site-packages (from pynput<2.0,>=1.7->streamdeck-ui) (0.31)
Requirement already satisfied: shiboken2==5.15.2 in ./.local/lib/python3.9/site-packages (from pyside2<6.0,>=5.13->streamdeck-ui) (5.15.2)
Building wheels for collected packages: evdev
  Building wheel for evdev (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/linuxbrew/.linuxbrew/opt/python@3.9/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3i1s9rxx/evdev_fdbfb886a3674f04a0ef30de528618fd/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3i1s9rxx/evdev_fdbfb886a3674f04a0ef30de528618fd/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-7hl_z1ee
       cwd: /tmp/pip-install-3i1s9rxx/evdev_fdbfb886a3674f04a0ef30de528618fd/
  Complete output (25 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/evdev
  copying evdev/uinput.py -> build/lib.linux-x86_64-3.9/evdev
  copying evdev/util.py -> build/lib.linux-x86_64-3.9/evdev
  copying evdev/eventio.py -> build/lib.linux-x86_64-3.9/evdev
  copying evdev/events.py -> build/lib.linux-x86_64-3.9/evdev
  copying evdev/genecodes.py -> build/lib.linux-x86_64-3.9/evdev
  copying evdev/eventio_async.py -> build/lib.linux-x86_64-3.9/evdev
  copying evdev/ff.py -> build/lib.linux-x86_64-3.9/evdev
  copying evdev/__init__.py -> build/lib.linux-x86_64-3.9/evdev
  copying evdev/ecodes.py -> build/lib.linux-x86_64-3.9/evdev
  copying evdev/device.py -> build/lib.linux-x86_64-3.9/evdev
  copying evdev/evtest.py -> build/lib.linux-x86_64-3.9/evdev
  running build_ext
  running build_ecodes
  writing ecodes.c (using /usr/include/linux/input.h /usr/include/linux/input-event-codes.h /usr/include/linux/uinput.h)
  building 'evdev._input' extension
  creating build/temp.linux-x86_64-3.9
  creating build/temp.linux-x86_64-3.9/evdev
  gcc-5 -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -I/home/linuxbrew/.linuxbrew/include -I/home/linuxbrew/.linuxbrew/opt/openssl@1.1/include -I/home/linuxbrew/.linuxbrew/opt/sqlite/include -I/home/linuxbrew/.linuxbrew/opt/python@3.9/include/python3.9 -c evdev/input.c -o build/temp.linux-x86_64-3.9/evdev/input.o -std=c99 -Wno-error=declaration-after-statement
  error: command 'gcc-5' failed: No such file or directory
  ----------------------------------------
  ERROR: Failed building wheel for evdev
  Running setup.py clean for evdev
Failed to build evdev
Installing collected packages: evdev, python3-xlib, pyside2, pynput, pillow, streamdeck-ui
    Running setup.py install for evdev ... error
    ERROR: Command errored out with exit status 1:
     command: /home/linuxbrew/.linuxbrew/opt/python@3.9/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3i1s9rxx/evdev_fdbfb886a3674f04a0ef30de528618fd/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3i1s9rxx/evdev_fdbfb886a3674f04a0ef30de528618fd/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-nbmenkaq/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/riccardoerra/.local/include/python3.9/evdev
         cwd: /tmp/pip-install-3i1s9rxx/evdev_fdbfb886a3674f04a0ef30de528618fd/
    Complete output (24 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    creating build/lib.linux-x86_64-3.9/evdev
    copying evdev/uinput.py -> build/lib.linux-x86_64-3.9/evdev
    copying evdev/util.py -> build/lib.linux-x86_64-3.9/evdev
    copying evdev/eventio.py -> build/lib.linux-x86_64-3.9/evdev
    copying evdev/events.py -> build/lib.linux-x86_64-3.9/evdev
    copying evdev/genecodes.py -> build/lib.linux-x86_64-3.9/evdev
    copying evdev/eventio_async.py -> build/lib.linux-x86_64-3.9/evdev
    copying evdev/ff.py -> build/lib.linux-x86_64-3.9/evdev
    copying evdev/__init__.py -> build/lib.linux-x86_64-3.9/evdev
    copying evdev/ecodes.py -> build/lib.linux-x86_64-3.9/evdev
    copying evdev/device.py -> build/lib.linux-x86_64-3.9/evdev
    copying evdev/evtest.py -> build/lib.linux-x86_64-3.9/evdev
    running build_ext
    ecodes.c already exists ... skipping build_ecodes
    building 'evdev._input' extension
    creating build/temp.linux-x86_64-3.9
    creating build/temp.linux-x86_64-3.9/evdev
    gcc-5 -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -I/home/linuxbrew/.linuxbrew/include -I/home/linuxbrew/.linuxbrew/opt/openssl@1.1/include -I/home/linuxbrew/.linuxbrew/opt/sqlite/include -I/home/linuxbrew/.linuxbrew/opt/python@3.9/include/python3.9 -c evdev/input.c -o build/temp.linux-x86_64-3.9/evdev/input.o -std=c99 -Wno-error=declaration-after-statement
    error: command 'gcc-5' failed: No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/linuxbrew/.linuxbrew/opt/python@3.9/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3i1s9rxx/evdev_fdbfb886a3674f04a0ef30de528618fd/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3i1s9rxx/evdev_fdbfb886a3674f04a0ef30de528618fd/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-nbmenkaq/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/riccardoerra/.local/include/python3.9/evdev Check the logs for full command output.
```
FYI `python3 --version` returns `Python 3.9.6`.

**Comment by prasket** [comment]
I am also running POP_OS 21.04. I was able to install streamdeck-ui by using [pipenv](https://pipenv.pypa.io/en/latest/) as is part of my normal Python workflow. Might give that a shot OP.

**Comment by idoodler** [comment]
I have had no issue installing it, tho I am unable to run it. it fails with the following error message:

`Could not open HID device.`

**Comment by mstipetic** [comment]
@idoodler did you figure out any solution? I recently did a Pop OS reinstall and now it's not working

**Comment by dodgyrabbit** [comment]
@mstipetic Did you follow these instructions after reinstall?
https://github.com/timothycrosley/streamdeck-ui#manual-installation

Do you get a similar error - if so, please provide the details.

Looking at the error above - it appears that `gcc-5` (a C compiler) is missing. How this stuff works exactly I don't understand to be honest - but it is possible that a clean PopOS install does not come with certain dependencies.

A shot in the dark, but try:
```
sudo apt install python3-dev
```
and then retry the streamdeck install.

**Comment by dodgyrabbit** [comment]
FYI I just downloaded PopOS 2010, did a clean install and followed the instructions. Everything worked as expected.
One critical step not to be ignored: after adding the udev rules **you must unplug and replug** the streamdeck back in. You will get the error `Could not open HID device` if you don't.

**Comment by mstipetic** [comment]
@dodgyrabbit Just to get things resolved - it works now. Turns out I've been a typical pain-in-the-ass user and somehow haven't put in the udev rules, even though I was 100% certain I did.
I'd also like to add that I am a bit in shock that you'd go through all this trouble - installing popos twice - in order to troubleshoot my issue, I have no idea how to respond. If there's anything I can do to return the favor please let me know! I'll do my best to try and contribute to the project when I get some time

**Comment by dodgyrabbit** [comment]
No problem @mstipetic , glad you got it working. I was curious about PopOS and I use VirtualBox to test various OS, doesn't take too much effort. Since it's based on Ubuntu I was pretty sure it's going to work. The latest PopOS release looks very nice.

While doing all this I found that one could refresh the udev rules with `sudo udevadm trigger`. The reload rules option in the instruction doesn't actually do anything, since udev already monitors for new rules. I'm going to update the documentation, hopefully makes it simpler with one less thing to do.

**Comment by SumNeuron** [comment]
@dodgyrabbit I am using pop-os freshed installed and I am struggling with this. It gives 
```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, xcb.

[1]    48803 IOT instruction (core dumped)  streamdeck

```

**Comment by dodgyrabbit** [comment]
@SumNeuron Do you have this installed?
```
sudo apt install python3-pip libhidapi-libusb0 libxcb-xinerama0
````

Specifically **libxcb-xinerama0** which is a dependency that is missing on Ubuntu based machines for QT.

**Comment by Menachem-D** [comment]
Any advice?
I'm getting this error:

 ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bz8e0yi_/evdev/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bz8e0yi_/evdev/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-gwy81c0x
       cwd: /tmp/pip-install-bz8e0yi_/evdev/
  Complete output (37 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/evdev
  copying evdev/util.py -> build/lib.linux-x86_64-3.8/evdev
  copying evdev/__init__.py -> build/lib.linux-x86_64-3.8/evdev
  copying evdev/genecodes.py -> build/lib.linux-x86_64-3.8/evdev
  copying evdev/uinput.py -> build/lib.linux-x86_64-3.8/evdev
  copying evdev/ff.py -> build/lib.linux-x86_64-3.8/evdev
  copying evdev/eventio_async.py -> build/lib.linux-x86_64-3.8/evdev
  copying evdev/ecodes.py -> build/lib.linux-x86_64-3.8/evdev
  copying evdev/evtest.py -> build/lib.linux-x86_64-3.8/evdev
  copying evdev/eventio.py -> build/lib.linux-x86_64-3.8/evdev
  copying evdev/events.py -> build/lib.linux-x86_64-3.8/evdev
  copying evdev/device.py -> build/lib.linux-x86_64-3.8/evdev
  running build_ext
  running build_ecodes
  The 'linux/input.h' and 'linux/input-event-codes.h' include files
  are missing. You will have to install the kernel header files in
  order to continue:
  
      yum install kernel-headers-$(uname -r)
      apt-get install linux-headers-$(uname -r)
      emerge sys-kernel/linux-headers
      pacman -S kernel-headers
  
  In case they are installed in a non-standard location, you may use
  the '--evdev-headers' option to specify one or more colon-separated
  paths. For example:
  
      python setup.py \
        build \
        build_ecodes --evdev-headers path/input.h:path/input-event-codes.h \
        build_ext --include-dirs  path/ \
        install
  ----------------------------------------
  ERROR: Failed building wheel for evdev
  Running setup.py clean for evdev
Failed to build evdev
Installing collected packages: evdev, pynput, streamdeck-ui
    Running setup.py install for evdev ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bz8e0yi_/evdev/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bz8e0yi_/evdev/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-__zcwdre/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/mendy/.local/include/python3.8/evdev
         cwd: /tmp/pip-install-bz8e0yi_/evdev/
    Complete output (39 lines):
    running install
    /home/mendy/.local/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/evdev
    copying evdev/util.py -> build/lib.linux-x86_64-3.8/evdev
    copying evdev/__init__.py -> build/lib.linux-x86_64-3.8/evdev
    copying evdev/genecodes.py -> build/lib.linux-x86_64-3.8/evdev
    copying evdev/uinput.py -> build/lib.linux-x86_64-3.8/evdev
    copying evdev/ff.py -> build/lib.linux-x86_64-3.8/evdev
    copying evdev/eventio_async.py -> build/lib.linux-x86_64-3.8/evdev
    copying evdev/ecodes.py -> build/lib.linux-x86_64-3.8/evdev
    copying evdev/evtest.py -> build/lib.linux-x86_64-3.8/evdev
    copying evdev/eventio.py -> build/lib.linux-x86_64-3.8/evdev
    copying evdev/events.py -> build/lib.linux-x86_64-3.8/evdev
    copying evdev/device.py -> build/lib.linux-x86_64-3.8/evdev
    running build_ext
    running build_ecodes
    The 'linux/input.h' and 'linux/input-event-codes.h' include files
    are missing. You will have to install the kernel header files in
    order to continue:
    
        yum install kernel-headers-$(uname -r)
        apt-get install linux-headers-$(uname -r)
        emerge sys-kernel/linux-headers
        pacman -S kernel-headers
    
    In case they are installed in a non-standard location, you may use
    the '--evdev-headers' option to specify one or more colon-separated
    paths. For example:
    
        python setup.py \
          build \
          build_ecodes --evdev-headers path/input.h:path/input-event-codes.h \
          build_ext --include-dirs  path/ \
          install
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bz8e0yi_/evdev/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bz8e0yi_/evdev/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-__zcwdre/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/mendy/.local/include/python3.8/evdev Check the logs for full command output.

**Comment by domgreen** [comment]
If anyone else has this issue on PopOS! I managed to fix it with the following:
```
sudo apt install libxcb-cursor0
```

**Comment by Menachem-D** [comment]
Thanks. I returnd my stream deck after giving up on it

**Comment by kyledoesdev** [comment]
> If anyone else has this issue on PopOS! I managed to fix it with the following:
> 
> ```
> sudo apt install libxcb-cursor0
> ```

Thank you bro this worked for me.
