### ISSUE TITLE
Does it work with the Elgato Stream Deck Mini?

### ISSUE THREAD

**Issue by LemmingAvalanche** [timothycrosley/streamdeck-ui#16]
Do you know if your fine program works with the Elgato Stream Deck Mini?

**Comment by espoelstra** [comment]
This supports the Stream Deck Original both v1 and v2 (006d and 0060 device IDs), the Stream Deck Mini, and the Stream Deck XL.

**Comment by LemmingAvalanche** [comment]
Thanks!
