### ISSUE TITLE
Package "python3.8-dev" and Python library "setuptools" required for installation

### ISSUE THREAD

**Issue by helioseven** [timothycrosley/streamdeck-ui#163]
Just tried installing streamdeck-ui for the first time, ran into two hitches both of which were relatively minor but worth mentioning, I think. I'm running Linux Mint 19.1, but this would apply to any system I'm pretty sure. To add to that, my default python3 version is 3.6.9, so I installed a fresh copy of 3.8.0 in parallel with the following results (which is also why I'm running `python3.8 -m pip` instead of just `pip3`).

First, python3-xlib-0.15 balks on `ModuleNotFoundError: No module named 'setuptools'`. Solution is easy enough: `python3.8 -m pip install setuptools` to resolve.

Then, evdev compilation gives `fatal error: Python.h: No such file or directory`. A bit of google-fu and this boils down to missing dev packages. System default python3-dev packages are 3.6.9 of course, so `sudo apt-get install python3.8-dev` set me straight.

Proposed Solutions:
- Mentioning python3.8-dev requirement in "Linux Quick Start" section of README.md.
- Modifying streamdeck-ui/scripts/ubuntu_install.sh to add `pip3 install -U pip setuptools`, just `pip3 install setuptools`, or something similar just before line 17. Same edit to streamdeck-ui/scripts/fedora_install.sh and mentioning it in README.md as well, probably.

**Comment by dodgyrabbit** [comment]
Old case. Closing.
