### ISSUE TITLE
Opening favorite with cmd+(1,2,3...)

### ISSUE THREAD

**Issue by jrenoux** [timothycrosley/streamdeck-ui#170]
Hi there, 

I just installed this ui for my streamdeck Original V2, and it works really nice so far. The only thing I'm not managing to do it to use it to open my favorites app to do something in them. 
For instance, if I want to open my emacs (which is favorited), on the keyboard I'd type "cmd+4". 
However, if I put this combination in streamdeck_ui, it presses cmd (and therefore open ubuntu's activities panel) and types a "4" wherever my mouse cursor happened to be at this moment. 
Other combinations with cmd seem to work fine, only "cmd+number" seems to have this behavior. Has anyone encountered this issue?

**Comment by oparada1988** [comment]
> Hi there,
> 
> I just installed this ui for my streamdeck Original V2, and it works really nice so far. The only thing I'm not managing to do it to use it to open my favorites app to do something in them. For instance, if I want to open my emacs (which is favorited), on the keyboard I'd type "cmd+4". However, if I put this combination in streamdeck_ui, it presses cmd (and therefore open ubuntu's activities panel) and types a "4" wherever my mouse cursor happened to be at this moment. Other combinations with cmd seem to work fine, only "cmd+number" seems to have this behavior. Has anyone encountered this issue?



try using the terminal command to open emac in the Command section, for example on my system I have a key to open spotify, the terminal command is "spotify" and it opens right up! hope that helps :-)

**Comment by jrenoux** [comment]
Unfortanetely that does not quite solve my issue. The advantage of using the favorite is that if the window is already open, it will open it, and if not it will open a new one. The terminal commend will usually open a new one even if there is already one opened. 

For now I found a workaround by writing my own scripts with xdotool, but it seems like a non-expected behavior that this shortcut specifically (cmd+1) would not work when everything else does.

**Comment by LowSkyOrbit** [comment]
Similar issue trying to us show desktop command:

`Ctrl + Cmd + D `

**Comment by dodgyrabbit** [comment]
I had a look at this and the root cause is with pynput, the library we are using for simulating keypresses.
Probably the best solution for now is to at least document this in the known-issues or readme. This works for me:

`xdotool key "Super_L+4"`

**Comment by dodgyrabbit** [comment]
Updated docs.
