### ISSUE TITLE
Intermittent mouse freeze

### ISSUE THREAD

**Issue by toro-** [timothycrosley/streamdeck-ui#172]
I've found that when I am using streamdeck-UI, my mouse input will freeze/stop. In order to restore it, I need to unplug and plug the mouse (steamdeck input, keyboard input continue to work fine)

For info:

- OS: Manjaro Linux x86_64 
- Kernel: 5.15.2-2-MANJARO 
- DE Xfce 4.16
- CPU: AMD Ryzen 5 2600 (12) @ 3.400GHz 
- GPU: AMD ATI Radeon RX 580
- Mouse: Razer Deathadder Chroma

Using [Polychromatic](https://github.com/polychromatic/) and [openrazer](https://github.com/openrazer/openrazer) - have been using these for sometime with no issues and continue to have no issues until streamdeck-ui is used.

**Comment by dodgyrabbit** [comment]
It could be a USB power or bandwidth issue.
See https://github.com/timothycrosley/streamdeck-ui#known-issues

Try a different port, removing other power hungry USB devices or an externally powered USB hub if you have one.
