### ISSUE TITLE
Aur install broken + from source seems broken to.

### ISSUE THREAD

**Issue by Data-007** [timothycrosley/streamdeck-ui#173]
Arch linux (Arcolinux) installing from the AUR is broken,
`==> ERROR: A failure occurred in prepare().
    Aborting...
error: failed to build 'streamdeck-ui-git-r270.d3cf85e-1':`

Installing from source.
'pip3 install git+https://github.com/timothycrosley/streamdeck-ui
Traceback (most recent call last):
  File "/usr/bin/pip3", line 33, in <module>
    sys.exit(load_entry_point('pip==20.3.4', 'console_scripts', 'pip3')())
  File "/usr/bin/pip3", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/cmdoptions.py", line 25, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 8, in <module>
    from pip._vendor.progress.bar import Bar, FillingCirclesBar, IncrementalBar
ModuleNotFoundError: No module named 'pip._vendor.progress'
'

Installation was working this morning. I rebooted machine and Streamdeck would not run.
I have uninstalled all and tried reinstall  with the above results.

Previously installed packages please see below.

![previous installed packages](https://user-images.githubusercontent.com/53057579/145679553-1a948ed3-ad09-4dfb-bdd4-c19901defed7.png)

**Comment by crstian19** [comment]
I have this problem when I try run it

![image](https://user-images.githubusercontent.com/21632768/145710435-b5510d25-dc98-437d-a89e-a7c133828b8e.png)

**Comment by Data-007** [comment]
I have mine fixed a simple reinstall off the OS Arcolinux.
Perhaps a more robust/easier way of fixing it could be worked out.

**Comment by crstian19** [comment]
I was on testing repo, I just disable testing repositories and make -Syuu to downgrade. All of it is because on testing repositories now all python is 3.10.

**Comment by AlexanderCurl** [comment]
I was able to fix it, with removing the `streamdeck-ui-git` from my Arch, cleared the cache with `pacman -Scc`
Then grabbed the AUR PKGBUILD and the corresponding `60-streamdeck.rules` files, put in the directory and run `makepkg -s`
Then, looks like if someone using Chaotic-AUR, as in my case I am, the `python-pynput` package doesn't register as a module, and the program fails to start as pynput missing.
So as a workaround I ended up installing via pip:
`sudo python -m pip install pynput`
And now it works again.

**Comment by MrCheeze446** [comment]
![image](https://user-images.githubusercontent.com/30207076/145874610-f3c3c819-7b0a-459c-978b-5dac7537ea8a.png)
Doesn't work on my machine, used the workaround @AlexanderCurl mentioned above.

**Comment by MrCheeze446** [comment]
Using the pip install works for me though.

**Comment by AlexanderCurl** [comment]
> ![image](https://user-images.githubusercontent.com/30207076/145874738-22b36371-ad11-400c-a8f4-d4532c73f595.png)
> 
> Doesn't work on my machine, used the workaround @AlexanderCurl mentioned above.

`sudo python -m pip install streamdeck` will help.

**Comment by redgloboli** [comment]
you need to re-install python-elgato-streamdeck like yay -S aur/python-elgato-streamdeck, or update your system in few minutes again.

**Comment by redgloboli** [comment]
python-pynput should be updated too i guess, maybe there will be a 1.7.5-2 soon too.

**Comment by MrCheeze446** [comment]
> > ![image](https://user-images.githubusercontent.com/30207076/145874738-22b36371-ad11-400c-a8f4-d4532c73f595.png)
> > Doesn't work on my machine, used the workaround @AlexanderCurl mentioned above.
> 
> `sudo python -m pip install streamdeck` will help.

pftt probably should've tried that, what you've mentioned will probably fix it then.

**Comment by ShadowReviews** [comment]
I was seemingly able to fix it by just doing `paru -S (pacman -Qoq /usr/lib/python3.9) --rebuild` which rebuilt all my AUR packages from 3.9, but this was the only one left anyway.

I believe I had previously already updated `python-pynput` with Paru, so try updating that and then rebuilding Streamdeck-UI. I've restarted my WM a few times which triggers Streamdeck-UI on startup and it's worked every time, I haven't tried sleeping, hibernating, or restarting though so I guess I'll find out later.

**Comment by Cinux90** [comment]
> I have this problem when I try run it
> 
> ![image](https://user-images.githubusercontent.com/21632768/145710435-b5510d25-dc98-437d-a89e-a7c133828b8e.png)

 I installed streamdeck-ui-git and the issue is gone for me.
Of course this will not solve the issue. But if you need the streamdeck for daily work its a good workaround.

**Comment by Data-007** [comment]
I have reinstalled my machine (after faulty graphics card upgrade).
I find that its impossible to install from arch repo's...... and installing from source I get

ERROR: Package 'streamdeck-ui' requires a different Python: 3.10.1 not in '<3.10,>=3.8'

I need streamdeck any chance of uping your python level?

**Comment by dodgyrabbit** [comment]
> I need streamdeck any chance of uping your python level?
This has been done.
