### ISSUE TITLE
Text Configuration

### ISSUE THREAD

**Issue by WMRamadan** [timothycrosley/streamdeck-ui#190]
**Problem:**

Text cannot be placed on top of the image, nor can it be resized.

**Solution:**

User should be able to set the text on top of the icon or below it as with original Elgato software. Also the user should be able to set the size of the text so it can fit better when needed.

**Specs:**

- Ubuntu 21.04
- Stream Deck UI (1.1.2)

**Comment by dodgyrabbit** [comment]
This is an open source project run by volunteers with limited time. Unfortunately parity to the commercial version is going to be unlikely. However, having some of these features would be nice for sure.
