### ISSUE TITLE
Ability to run shell scripts

### ISSUE THREAD

**Issue by sgilissen** [timothycrosley/streamdeck-ui#191]
Hi, 

Running Fedora 35 with Cinnamon. 
I'm trying to run a shell script as command in streamdeck-ui, but it seems that this isn't working at the moment. 

I've tried to prepend the command with "bash", "sh" and a plain old dot. 
This may be a PEBKAC issue though, so if I'm doing something wrong I'm all ears :-) 

Thanks!

**Comment by dodgyrabbit** [comment]
I'm not using Fedora but I'll try to help in general:

1. Use the console that you launched streamdeck from to help you diagnose what is going wrong. You should get an appropriate error message when you press the button.
2. Make sure you use a full path. For example /home/yourname/yourscript.sh. It will not expand a path like ~/yourscript.sh
3. Make sure you have set execute permissions on the file. `chmod +x yourscript.sh`

**Comment by sgilissen** [comment]
Hi, 

Thanks for the response!
Unfortunately, I've tried all that. 
After some testing, it seems that communication between the Streamdeck and streamdeck-ui stops working whenever I call a shell script. 

The way I've tested this, is the following: 
Made a new button, which points to the script in the "command" inputfield, using the full path. Script is chmodded +x
I have several different buttons which control Spotify. For example, the play/pause button:
```dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause```

This works fine, however when I use the new button that points at my script, none of the buttons work anymore. 
Changing the tab in the UI does reflect the page on the Streamdeck device, however. 
This is the output I see in the terminal:

```
method return time=1643762277.920744 sender=:1.1536 -> destination=:1.3991 serial=882 reply_serial=2
method return time=1643762278.931826 sender=:1.1536 -> destination=:1.3992 serial=886 reply_serial=2
method return time=1643762280.998262 sender=:1.1536 -> destination=:1.3993 serial=890 reply_serial=2
method return time=1643762281.599617 sender=:1.1536 -> destination=:1.3994 serial=894 reply_serial=2
```

Not sure what's going on here.

Thanks in advance!

-Steve

**Comment by dodgyrabbit** [comment]
The you output provided must be coming from your own script - does not seem related to streamdeck.

Can you provide a minimum reproduction of this problem? I'm not able to reproduce.
Provide a .sh file and ideally, your streamdeck config file (`~/.streamdeck_ui.json`), or an excerpt from the file if it contains private info.

Also - have you simple examples, like a script with just
```
#!/bin/bash
ls
```
and see if you still get the hangups if runs?

**Comment by hugeblank** [comment]
I was having this exact same issue. `#!/bin/<bash/zsh/whatever>` in the file fixed the issue. I think that the script should be able to run regardless of the shebang, however.

**Comment by dodgyrabbit** [comment]
Thanks for the comment. I'm still unable to reproduce, if someone can provide a script file and steps to reproduce, I'll take a look if there's anything we can do to make it more robust.

**Comment by sgilissen** [comment]
Hi, 

I've tested a script with shebang, and that seems to work!
Thanks to @hugeblank for the tip. 

Might be a good idea to add this to the documentation? 
While it's best practice to add a shebang, I'm fairly certain that this gets forgotten quite a lot. 

In any case, problem solved!

**Comment by SumNeuron** [comment]
I would like to toss a related question into this mix. I have a shell script "my_script.sh" that I can set to run by configuring `command ` to be `bash -c "~/path/to/script/my_script.sh"` and this works. However, I can not easily kill the process when launched through stream deck. If we are adding docs, it would be nice to know how to kill a script this way and / or make the button toggle-able (once for start script, again for stop script)

**Comment by hugeblank** [comment]
@SumNeuron This isn't necessarily as elegant as a toggleable button, but I think you're looking for something like this:
```bash
pid=`ps -f | grep "my_script\.sh$" | awk '{print $2}'`
kill $pid
```
The `$` at the end of the regular expression in `grep` means that it searches for the script name, and then an end of line. This has the advantage that it doesn't detect the grep expression itself. This will also kill off all instances of `my_script.sh`, in case there's multiple. If you want to kill off only the specific `my_script` instance spun off by the streamdeck, a more advanced bodge would be necessary, like finding the pid of the streamdeck-ui app (probably through a startup script, that *then* starts the app) and comparing it to the parent pid.

**Comment by sgilissen** [comment]
> I would like to toss a related question into this mix. I have a shell script "my_script.sh" that I can set to run by configuring `command ` to be `bash -c "~/path/to/script/my_script.sh"` and this works. However, I can not easily kill the process when launched through stream deck. If we are adding docs, it would be nice to know how to kill a script this way and / or make the button toggle-able (once for start script, again for stop script)

This may be a new issue and/or feature request (e.g. toggleable buttons). I've never used the "official" streamdeck client, but I don't know if they have toggleable buttons there.

**Comment by dsm-72** [comment]
@hugeblank I tried that didn't quite work. It doesn't' have to be a toggleable button per se @sgilissen  more like one button starts a script another captures and kills it would be acceptable as well. If there was a pre-baked macro for it e.g. `streamdeck-ui terminate-activity-from-start-button-id=1`
