### ISSUE TITLE
Keybind Picker

### ISSUE THREAD

**Issue by Battle420** [timothycrosley/streamdeck-ui#193]
Hi!  
I'm kinda dumb with how to setup proper keybindings, and there are also some keys that I don't know the name of, so I can't set them up.  

Therefore, it would be great if by pressing a button, you could just press the key combination and it would spit out the the required text to put on the "Press Keys" box

This is the combination that I want to press (that I didn't see on the [Docs](https://pynput.readthedocs.io/en/latest/_modules/pynput/keyboard/_base.html#Key)): 
![key](https://user-images.githubusercontent.com/52968657/151062362-f496c3a9-f969-43d4-b804-2cd5374f435d.jpeg)

**Comment by dodgyrabbit** [comment]
If you want it to output `:`, then simply put `:` in the `Press Keys:` field. There is no need to use modifiers in that case.

**Comment by Battle420** [comment]
Okay, thanks for telling me.
