### ISSUE TITLE
Text Top/Bottom Placement

### ISSUE THREAD

**Issue by WMRamadan** [timothycrosley/streamdeck-ui#198]
**Problem:**

You cannot place text on top of the Icon, it can only be placed along the bottom of the Icon.

**Solution:**

Add a feature to adjust text placement to either top or bottom of the Icon.

Specs:
Ubuntu Linux 21.10
Kernel 5.13.0-28-generic

**Comment by izzy** [comment]
It would also help if you could insert linebreaks or generally some form of rich text - right now for every button I want to make/edit that needs more than one short word of text I need to open Krita which is kind of annoying.

**Comment by dodgyrabbit** [comment]
Vertical text alignment has been implemented. See #206
