### ISSUE TITLE
Streamdeck software wont run from install.

### ISSUE THREAD

**Issue by Data-007** [timothycrosley/streamdeck-ui#201]
Hi Pieter, Timothy, Comunity
A fresh install of the OS, so I thought I would do it proper, as per your excellent instructions previously TY.

I did the following,

Installed python3
Installed cairosvg
pip3 install streamdeck-ui 

I noted that this was installed in a SubDir/..folder so I CDed  that directory, and ls. 
`[steve@steve-main bin]$ ls
cairosvg          pyside2-lupdate  pyside2-uic
pyside2-designer  pyside2-rcc      streamdeck`

I then tried to run `streamdeck`, but it failed with the result below.

`[steve@steve-main bin]$ streamdeck
Waiting for Stream Deck(s)...
Traceback (most recent call last):
  File "/home/steve/.local/bin/streamdeck", line 8, in <module>
    sys.exit(start())
  File "/home/steve/.local/lib/python3.10/site-packages/streamdeck_ui/gui.py", line 680, in start
    items = api.open_decks().items()
  File "/home/steve/.local/lib/python3.10/site-packages/streamdeck_ui/api.py", line 105, in open_decks
    deck.open()
  File "/home/steve/.local/lib/python3.10/site-packages/StreamDeck/Devices/StreamDeck.py", line 153, in open
    self.device.open()
  File "/home/steve/.local/lib/python3.10/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 352, in open
    self.device_handle = self.hidapi.open_device(self.device_info['path'])
  File "/home/steve/.local/lib/python3.10/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 181, in open_device
    raise TransportError("Could not open HID device.")
StreamDeck.Transport.Transport.TransportError: Could not open HID device.`

I this stage I was expecting the window to configure streamdeck to appear.

I unplugged and replugged still the same result. Ho hum
Note: I also tried ./streamdeck

The thought that went thru my mind was the units/packages from aur.
I installed AUR,

 `python-elgato-streamdeck
streamdeck streamdeck-ui-git`

and retried streamdeck  After replugging the deck It worked, 

At this stage I test.
[steve@steve-main ~]$ pip3 show streamdeck-ui
Name: streamdeck-ui
Version: 1.1.3
Summary: A service, Web Interface, and UI for interacting with your computer using a Stream Deck
Home-page: None
Author: Timothy Crosley
Author-email: timothy.crosley@gmail.com
License: MIT
Location: /home/steve/.local/lib/python3.10/site-packages
Requires: python3-xlib, pillow, pyside2, streamdeck, pynput
Required-by: 

Version 1,1.3

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
**I then tried removing the aur packages** 

 `python-elgato-streamdeck
streamdeck streamdeck-ui-git`

and tried running the streamdeck from within the Dir and it wont run.

I have tried various permutations, even rebooting but the end is I get similar error output,
`[steve@steve-main bin]$ streamdeck
Waiting for Stream Deck(s)...
Traceback (most recent call last):
  File "/home/steve/.local/bin/streamdeck", line 8, in <module>
    sys.exit(start())
  File "/home/steve/.local/lib/python3.10/site-packages/streamdeck_ui/gui.py", line 680, in start
    items = api.open_decks().items()
  File "/home/steve/.local/lib/python3.10/site-packages/streamdeck_ui/api.py", line 105, in open_decks
    deck.open()
  File "/home/steve/.local/lib/python3.10/site-packages/StreamDeck/Devices/StreamDeck.py", line 153, in open
    self.device.open()
  File "/home/steve/.local/lib/python3.10/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 352, in open
    self.device_handle = self.hidapi.open_device(self.device_info['path'])
  File "/home/steve/.local/lib/python3.10/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 181, in open_device
    raise TransportError("Could not open HID device.")
StreamDeck.Transport.Transport.TransportError: Could not open HID device.`

##copied from above not actual evertime.

OS Arcolinux

Pieter I am only following your comments which you excellently made, with how to install yours and Timothys program.
I will be reinstalling `OS` on Mon also so can test any help I get from the community or from yourselves. As to where I went wrong.

#############################################################################

One feature I would like to see added to the program is a toggle to set to auto launch the program at startup,
preferably from withing the file menu as preferences.

**Comment by dodgyrabbit** [comment]
Hi @Data-007 ,

I'm only going based on what you wrote here. You did not mention installing the udev rules after the clean install. The streamdeck-ui pip installer does **not** add the required udev rules.  Since you didn't mention it, I can only conclude you didn't add those udev rules and hence you will not have access to the device, and the error makes sense (`Could not open HID device`).

I'm not familiar with aur and what it installs. However, it's quite possible something in there installs the required udev rules and that is why it works.

> Installed cairosvg
This is not needed in the currently released version (1.1.3) - but that is unrelated the problem you mention.

**Comment by dodgyrabbit** [comment]
Maybe coincidence but someone had a very similar issue as you and may be application, please read through it:
https://github.com/timothycrosley/streamdeck-ui/issues/200

Also please note that this is out of date:
https://timothycrosley.github.io/streamdeck-ui/

Stick to this:
https://github.com/timothycrosley/streamdeck-ui#readme

Unfortunately I can't update the doc site myself.

**Comment by Data-007** [comment]
Thanks udev rules now working.

Please Add this to the next release when it comes.

One feature I would like to see added to the program is a toggle to set to auto launch the program at startup,
preferably from withing the file menu as preferences.

**Comment by dodgyrabbit** [comment]
Glad you got it working. Not sure where you got stuck - but if you have suggestions on making the install documentation clearer, please chime in.

I'm working on some other things at the moment and I believe there are some people who managed to achieve what you're asking for. Likely won't get to it anytime soon but thanks for the suggestion.
