### ISSUE TITLE
Issue with launching streamdeck with Debian 11

### ISSUE THREAD

**Issue by phils93** [timothycrosley/streamdeck-ui#204]
i am having this issue after a success in installation, and i am having this while trying to launch the command streamdeck on a Debian 11 on a virtual machine.
Traceback (most recent call last):
  File "/home/philippevm/.local/bin/streamdeck", line 8, in <module>
    sys.exit(start())
  File "/home/philippevm/.local/lib/python3.9/site-packages/streamdeck_ui/gui.py", line 185, in start
    build_buttons(ui, ui.cards.currentWidget())
  File "/home/philippevm/.local/lib/python3.9/site-packages/streamdeck_ui/gui.py", line 97, in build_buttons
    deck = api.get_deck(deck_id)
  File "/home/philippevm/.local/lib/python3.9/site-packages/streamdeck_ui/api.py", line 73, in get_deck
    return {"type": decks[deck_id].deck_type(), "layout": decks[deck_id].key_layout()}
KeyError: None

**Comment by Data-007** [comment]
Hi
Only a guess did you install/do the udev rules part ?
That's the part I forgot. Also with the latest version 
you can install a higher level of python > 3.10......
I am away to install myself.
--
Steve

**Comment by phils93** [comment]
Hello yes i did it and i have Python 3.9.2 and it's still not working

**Comment by dodgyrabbit** [comment]
Please provide more details.
Based on the call stack, it does not appear like the latest version is installed so let's confirm

Please run:
```
pip3 show streamdeck-ui
```
or this
```
python3 -m pip show streamdeck-ui
```

If it is in fact old - can you elaborate how you went about installing. Exact steps, link to website you used etc would be good to understand. 

Also what model Stream Deck are you using?

**Comment by phils93** [comment]
it works fine for me now thank you very much !
