### ISSUE TITLE
New version v2.0.3 does not apply brightness on startup

### ISSUE THREAD

**Issue by smarrk** [timothycrosley/streamdeck-ui#211]
**Describe the bug**

The brightness of the streamdeck ist not applied on startup, but only when the settings window is opened.

**To Reproduce**

1. Start streamdeck-ui
2. Brightness of streamdeck will be 100%
3. Open settings
4. Brightness settings are applied correctly

**Expected behavior**
Brightess is applied on startup (as before).

**Operating system (please complete the following information)**
 - OS: Manjaro 21.2.4
 - Desktop environment: i3wm
 - Python version: 3.10.2

**Stream Deck Version**
 - Mini

**Comment by dodgyrabbit** [comment]
Hi @smarrk , can you confirm if this was installed from [test.pypi.org](https://test.pypi.org/simple/) or the main pypi repo? A fix was committed prior to release to the main pypi repo and just want to confirm which version we're talking about.
In retrospect, I think the version should have been increased.

**Comment by smarrk** [comment]
Hi,

I installed from test.pypi.org as described in #206.
I reinstalled now from main repo and the brightness behaves as expected :+1:

Thanks for pointing me to the correct repo!
