### ISSUE TITLE
UI not allowing for button configuration/editing

### ISSUE THREAD

**Issue by OpenDataAlex** [timothycrosley/streamdeck-ui#213]
**Describe the bug**
After performing a fresh install and starting the UI up from terminal I get the UI, but am unable to add/configure buttons.  I imagine this is a Wayland issue.

**To Reproduce**
1. Follow manual installation instructions
2. Open terminal
3. run 'streamdeck'

**Screenshots**
![image](https://user-images.githubusercontent.com/244256/158717979-24b77c0a-6756-4694-b3d5-6d525334dd98.png)

**Operating system (please complete the following information)**
 - OS: Ubuntu 21.10
 - Desktop environment:  Gnome
 - Python version Python 3.9

**Stream Deck Version**
 - Mini

**Comment by dodgyrabbit** [comment]
Hi @OpenDataAlex - does the terminal that you launch it from show any errors?

The most common problem is that the udev rules are not properly configured:
https://github.com/timothycrosley/streamdeck-ui#manual-installation

**Comment by dodgyrabbit** [comment]
Could you try running a couple of these examples, to see if they work with your streamdeck mini:

https://github.com/abcminiuser/python-elgato-streamdeck/tree/master/src

You should in theory just be able to download the files and run it like so:
``` python3 example_basic.py ```

**Comment by dodgyrabbit** [comment]
Not reproducible and no more info. Please reopen if you've done more troubleshooting and have new info.
