### ISSUE TITLE
Sound coming from the app when playing a video

### ISSUE THREAD

**Issue by Jokod** [timothycrosley/streamdeck-ui#217]
**Describe the bug**
When I start a video that plays sound and I pause it.
I hear in my helmet a "beep beep" which lasts about twenty seconds.
Then stops, and starts again when the video is played again.
If I cut the application the noise no longer emits

**To Reproduce**
1. Have a headset plugged into the PC
2. Launch the application
3. Play a video that has sound and pause it
4. listen to the beep beep

**Expected behavior**
Would it be possible to know why the application emits noise and if it is possible to fix it?

**Operating system (please complete the following information)**
 - OS: Ubuntu 20.04
 - Desktop environment: Gnome
 - Python version: Python 3.9

**Stream Deck Version**
 - Stream Deck Original (V2)
 
 Thank You !

**Comment by dodgyrabbit** [comment]
> Would it be possible to know why the application emits noise and if it is possible to fix it?

This is definitely one of the weirder issues anyone has ever opened.  The application does not (purposefully) emit any sound. Are you able to post a link to a video/audio clip of the symptom?

Some ideas to try:
- Try using a different USB port. Perhaps there is some kind of interference.
- Does it only happen with your headset? What about using HDMI/screen speakers?
- Do you have Bluetooth? Can you try using a separate sound output.
