### ISSUE TITLE
How do I make one stream deck change the page on another | Some bug fixes confirmed working

### ISSUE THREAD

**Issue by EzequielBruni** [timothycrosley/streamdeck-ui#221]
**Please describe the problem would like to solve**
Simply put, I have two stream decks (classic and mini) and no idea how to make one stream deck change the page on another. Is there a reasonably simple command I could use to make that happen?

**Describe the solution you'd like**
Some documentation specifying what options we can use with streamdeck-ui in the CLI would be cool. I am a dummy not a programmer, so the more beginner-friendly, the better.

----

### Confirmed fixes

Problems aside, I wanted to thank you guys for this software. Wihtout it, one more PC in my home office would still be using Windows. I've noticed a couple of reported bugs that are no longer an issue... at least for me:

1. Two stream decks are working flawlessly side by side. #156 
2. Both the **Key Press** and the **Write Text** features are working flawlessly outside of the app on Fedora 35, whether the window is open or not.
    * Juuuust realized this may be because I use X, not Wayland. I can't switch until programs like Barrier or Synergy support Wayland.

Please let me know if there are any other beginner-friendly things you'd like me to test on Fedora.

**Comment by dodgyrabbit** [comment]
>  Is there a reasonably simple command I could use to make that happen?
No, not at the moment

Thanks for the feedback on the fixes. 
I'm going to close this case for now, as I believe the concept of programmatically interacting with a streamdeck will ultimately solve your use case, once that is implemented.
