### ISSUE TITLE
Numpad support

### ISSUE THREAD

**Issue by thiagosdm** [timothycrosley/streamdeck-ui#222]
**Please describe the problem would like to solve**
I would like to use numpad keys on a music software that requires a numpad key to be pressed.

**Describe the solution you'd like**
On the `Press keys` input, something like `numpad1` or `numpad-1` should trigger the Numpad-1 key.

**Comment by Pameloe** [comment]
The latest streamdeck-ui version actually added support for hex key codes in Key Press. For example, for numpad1 you could enter 0xFFB1. Check this manual for more hex key codes: https://www.tcl.tk/man/tcl8.6/TkCmd/keysyms.html. Scroll down to the KP section for all the numpad codes. Hope this helps!

**Comment by dodgyrabbit** [comment]
Thanks @Pameloe  you are correct. Simply use the Key Code (for example 0xFFBD for keypad `=`). The whole table is listed below and I tried a few - they seem to work fine.
```
KP_Space       0xFF80
KP_Tab         0xFF89
KP_Enter       0xFF8D
KP_F1          0xFF91
KP_F2          0xFF92
KP_F3          0xFF93
KP_F4          0xFF94
KP_Home        0xFF95
KP_Left        0xFF96
KP_Up          0xFF97
KP_Right       0xFF98
KP_Down        0xFF99
KP_Prior       0xFF9A
KP_Next        0xFF9B
KP_End         0xFF9C
KP_Begin       0xFF9D
KP_Insert      0xFF9E
KP_Delete      0xFF9F
KP_Multiply    0xFFAA
KP_Add         0xFFAB
KP_Separator   0xFFAC
KP_Subtract    0xFFAD
KP_Decimal     0xFFAE
KP_Divide      0xFFAF
KP_0           0xFFB0
KP_1           0xFFB1
KP_2           0xFFB2
KP_3           0xFFB3
KP_4           0xFFB4
KP_5           0xFFB5
KP_6           0xFFB6
KP_7           0xFFB7
KP_8           0xFFB8
KP_9           0xFFB9
KP_Equal       0xFFBD
```
