### ISSUE TITLE
Icons are left-aligned in 2.0.3

### ISSUE THREAD

**Issue by yktoo** [timothycrosley/streamdeck-ui#223]
After I upgraded `streamdeck-ui` from `1.1.3` to `2.0.3` all icons became left-aligned, and I see no option to change that. They used to be horizontally centered.

![image](https://user-images.githubusercontent.com/1675911/163212664-2086d0a2-d4a5-4f21-acda-7f5ae7ebd069.png)

Is it possible to center them as before, perhaps with some setting? All icons are 72x72 pixels.

**Stream Deck Version**
XL

**Comment by Data-007** [comment]
It must be something to do with upgrade or distro.
I have 2.0.3 on arch, and its fine.
![Streamdeck](https://user-images.githubusercontent.com/53057579/163437348-3667b369-97d2-4d2d-baf0-aee4448b5d39.png)

**Comment by yktoo** [comment]
@Data-007 What dimensions and format (PNG, SVG) do your icons have?

**Comment by Data-007** [comment]
H
![App_Amazon](https://user-images.githubusercontent.com/53057579/163573864-c529d80c-42e9-4768-8495-8a96dee02002.gif)
i
The Gifs are animated 128 X 128
Nordpass 272 X 223 png

The others are hand-made and various sizes, I don't think I have any SVG's on that page.
HIH

**Comment by yktoo** [comment]
Hmm. If I use a bigger icon than the recommended 72×72 pixels then it's properly downscaled and looks exactly like on your screenshot. The downside is though that it overlaps with the text.

Previously a smaller (72×72) icon would be centered horizontally, leaving space below for the text.

**Comment by dodgyrabbit** [comment]
I believe the XL native resolution is  96x96 for the XL, if you want to fill the whole screen. In the latest version the text is overlaid which gives you better control of the button space (i.e. you can decide if you want to make space for the text or not with your icon design). Previously it was impossible to use the whole button for the image with text.  The text can also be moved vertically.

I'm inclined to say "won't fix" as I'd want to work on some more critical issues. Thanks for understanding!
