### ISSUE TITLE
Udev rules doesn't work on Fedora (solved)

### ISSUE THREAD

**Issue by valwithoutfriends** [timothycrosley/streamdeck-ui#226]
Udev rules don't work on Fedora 35.

Using /etc/udev/rules.d/99-streamdeck.rules instead of 70-streamdeck.rules fixed that issue.

**Operating system**
 - Fedora Linux 35
 - Gnome 41.5
 - Python 3.10.4

**Stream Deck Version**
 - XL

**Comment by dodgyrabbit** [comment]
Thanks I'll take a look at Fedora 35 /etc/udev rules that comes standard. These rules are applied in lexical ordering, so it must be that something "after" 70-xxx disables the device again and hence why 99-xxx works.

**Comment by dodgyrabbit** [comment]
Not reproducible. Installed on a clean Fedora 36, with udev rule in file called 70-streamdeck.rules
