### ISSUE TITLE
Double button action

### ISSUE THREAD

**Issue by oparada1988** [timothycrosley/streamdeck-ui#229]
I was going over the issues page and I dont think I saw this yet, I was wondering if a feature to have a button with double command? For example:

1st state, press to have the stream start
then
2nd state press to have the stream stop.

each state would have its own unique icon and it would change depending on the state.

Thanks alot!

**Comment by dodgyrabbit** [comment]
Thanks for the note.
Yea, it's a bit hidden but the same idea is described [here](https://github.com/timothycrosley/streamdeck-ui/issues/99#issuecomment-823740821).
