### ISSUE TITLE
Libraries for Centos 7.7 

### ISSUE THREAD

**Issue by lee11lee** [timothycrosley/streamdeck-ui#23]
Hi,

does anyone have the correct libraries needed for Denton 7.7?
I’ve found a couple different one, but I’m not sure which one are correct..

Any help would be greatly appreciated.

lee

**Comment by xorbital** [comment]
I'll have a look into it, should be pretty close to fedora however.

**Comment by lee11lee** [comment]
Damn,so it‘s a nogo on centos? 😢

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by xorbital** [comment]
Oh, I'm sorry, I might have missed a word there :D I couldn't get **CentOS** to run

**Comment by lee11lee** [comment]
I finally got it to work. For those having the same problem, here is my list of what to do:

1. intall hid:
pip3 install hid

2. Install HID library
yum install hidapi

3. Install libusb
yum install libusb

4. install libudev (systemd-devel)
yum install systemd-devel

4.6 Rules
sudo tee /etc/udev/rules.d/10-streamdeck.rules << EOF
	SUBSYSTEMS=="usb", ATTRS{idVendor}=="0fd9", GROUP="users"
	EOF

5. Add the udev rules using your favorite text editor:
sudo nano /etc/udev/rules.d/99-streamdeck.rules

SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", MODE:="666", GROUP="plugdev"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0063", MODE:="666", GROUP="plugdev"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006c", MODE:="666", GROUP="plugdev"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006d", MODE:="666", GROUP="plugdev"

6. reload rules
sudo udevadm control --reload-rules

7. Unplug und replug device

8. pip3 install --user streamdeck_ui

9. streamdeck

**Comment by dodgyrabbit** [comment]
Created a doc how to install the very latest version on CentOS
https://github.com/timothycrosley/streamdeck-ui/blob/master/docs/centos.md
