### ISSUE TITLE
Cannot start streamdeck with PopOS 22.04

### ISSUE THREAD

**Issue by toolz0** [timothycrosley/streamdeck-ui#233]
Traceback (most recent call last):
  File "/home/todd/.local/bin/streamdeck", line 5, in <module>
    from streamdeck_ui.gui import start
ModuleNotFoundError: No module named 'streamdeck_ui'

Worked fine under PopOS 21.10, but after a live upgrade, gives the above error message.  Went through
the manual installation procedure again to make sure all dependencies were installed.

DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Pop!_OS 22.04 LTS"
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"

**Comment by dodgyrabbit** [comment]
Hi @toolz0 - you opened and closed. Did you figure out the problem? Maybe post here in case others run into the same issue.

**Comment by toolz0** [comment]
In place upgrade from 21.10 to 22.04 removed a lot of stuff that I expected to be there.  It does not appear that any apps were removed, including Streamdeck, but all my Perl modules were gone.  Some of the Streamdeck configs were still there, like udev, but other modules had been removed.  Streamdeck started working after running the installation procedure twice.
