### ISSUE TITLE
Streamdeck UI does not work after suspend

### ISSUE THREAD

**Issue by flajann2** [timothycrosley/streamdeck-ui#242]
**Describe the bug**
When I revive my computer from "sleep" or suspend, Streamdeck UI does not automatically reconnect to the hardware. I have to restart Streamdeck UI manually.

**To Reproduce**
1. Start Streamdeck UP
2. Put your computer into sleep or suspend mode.
3. Revive your computer from sleep
4. Attempt to operate the Streamdeck
5. You will note that the buttions on the Streamdeck will go black and that Streamdeck UI is nonresponsive.
6. Restaring Streamdeck reestablishes functionality.

**Expected behavior**
When reviving computer, the Streamdeck UI should automatically reconnect with the hardware.

**Operating system (please complete the following information)**
OS: Arch Linux x86_64
Kernel: 5.18.9-arch1-1
Resolution: 1440x2560, 1440x2560, 3840x2160
DE: Plasma 5.25.2
WM: KWin
Theme: ArchSmooth [Plasma], Breeze [GTK2/3]
Icons: [Plasma], breeze-dark [GTK2/3]
Terminal: tmux
CPU: AMD Ryzen Threadripper 3970X (64) @ 3.700GHz
GPU: NVIDIA GeForce RTX 3080 Ti
Memory: 36360MiB / 257586MiB
Python 3.10.5

**Stream Deck Version**
 -  XL

Thank you for the awesome product. Let's make it even more awesome!

**Comment by dodgyrabbit** [comment]
Can you confirm you are running version 2.0.4 of this software. This issue was fixed here:
https://github.com/timothycrosley/streamdeck-ui/issues/4
and seems to be working for several people.

If not, are there any errors or clues in the console output where you originally launched it from?

**Comment by dodgyrabbit** [comment]
@flajann2 Just checking if you are able to confirm if 2.0.4 work for you or not? What you describes sounds like 2.0.3 and prior behaviour.

**Comment by dodgyrabbit** [comment]
Please reopen if this issue persists with 2.0.4 and provided as much details as possible. Console output, behaviour, what it's plugged into etc.
