### ISSUE TITLE
Add support for new Stream Deck Mini (when python-elgato-streamdeck upgraded past 0.9.1)

### ISSUE THREAD

**Issue by victoriadrake** [timothycrosley/streamdeck-ui#248]
**Describe the bug**

Stream Deck doesn't appear to be recognized by `streamdeck-ui`. 

It appears to be connected as `Elgato Systems GmbH Stream Deck Mini` shows up with `lsusb`.

**To Reproduce**
1. Install `streamdeck-ui` with the precooked script (https://github.com/timothycrosley/streamdeck-ui/blob/master/scripts/ubuntu_install.sh)
2. Plug in Stream Deck Mini to USB port
3. Launch with terminal command `streamdeck` as instructed 

**Expected behavior**
The Stream Deck Mini should appear in the dropdown menu on the left.

**Screenshots**

![image](https://user-images.githubusercontent.com/24644237/182051964-b74b5ac4-9dba-4d82-a88d-b4f967be6347.png)

**Operating system (please complete the following information)**
 - OS: Ubuntu 22.04
 - Desktop environment: GNOME
 - Python version: Python 3.10.4 (also tried Python 3.8.12)

**Stream Deck Version**
 - Mini

**Comment by dodgyrabbit** [comment]
@RocketSEA the change was implemented 10h ago in the upstream library. Once they publish a new build, I will update streamdeck_ui to use it. A change to  /etc/udev/rules.d/70-streamdeck.rules will also be required.

**Comment by coljac** [comment]
@RocketSEA I followed what you tried, and was successful. I can use and configure the mini without any issues now.

**Comment by dodgyrabbit** [comment]
Version `2.0.5` has been published and now supports the new mini.
Please review the updated [readme](https://github.com/timothycrosley/streamdeck-ui/blob/master/README.md) to make the required changes to `/etc/udev/rules.d/70-streamdeck.rules`.

To upgrade, run:
```
pip install streamdeck_ui --upgrade
```
