### ISSUE TITLE
It'd be nice if I could see the actual icons when selecting one.

### ISSUE THREAD

**Issue by pblanton** [timothycrosley/streamdeck-ui#256]
When I click the [Image...] button to assign an image to a StreamDeck button, the "Open Image" dialog opens up but there isn't an option for me to see my images. I have to know what they are by their names...

![image](https://user-images.githubusercontent.com/1143649/188020890-a7256a81-2c76-4596-b8d0-5ff262248a03.png)

I'd like to have more view options for showing the icons and adjusting the size that they are rendered in the "Open Image" dialog. Here is the same folder as displayed in Dolphin...

![image](https://user-images.githubusercontent.com/1143649/188021185-fd750b5e-b876-46f5-8c07-49a7af130956.png)

BTW, I am running Kubuntu 22.04. Maybe this works properly in Gnome? But it's a sub-optimal experience in KDE.

**Comment by pblanton** [comment]
In Dolphin, this button ...

![image](https://user-images.githubusercontent.com/1143649/188021523-b5eeabb0-54ed-4f86-a7db-8fb27930466c.png)

Shows the images, but in the "Open Image" dialog in Stream Deck UI, it doesn't. The top image in my first post shows what it does in the "Open Image" dialog.

I have branched the code and am willing to experiment to see if I can modify the behavior. If you could just give me some quick pointers where to look in the code that'd help. If I can fix it, then I'll submit a pull req.

**Comment by dodgyrabbit** [comment]
I had a look and unfortunately the file selection dialog in PySide does not offer this feature. One would have to extend or write your own file selector, which is hardly worth the effort.

However, please note you can drag-drop images from your file explorer (Nautilus/Dolphin) onto the buttons - which gives you visual of the images while selecting.

I liked the idea though, thanks for the suggestion.
