### ISSUE TITLE
Dark Mode switch

### ISSUE THREAD

**Issue by oparada1988** [timothycrosley/streamdeck-ui#261]
Self explanitory, dark mode options in the file, or about menu kinda like how ProtonUp-QT has

![Screenshot from 2022-09-12 19-18-45](https://user-images.githubusercontent.com/4031078/189774758-220c970b-eaff-422d-bd49-3d84932e9fe4.png)

Sorry for opening a ticket for such mundane request

**Comment by Data-007** [comment]
Hi
I am on Plasma I have a dark theme installed :Breeze Dark
I find that with that selected that streamdeck-ui automatically follows
that theme. If dark it shows dark........ ...

![streamdeckuiDark](https://user-images.githubusercontent.com/53057579/189914220-01ca47a5-3268-48e7-a2f6-bff14a6257e5.png)

HIH

--
Data

**Comment by oparada1988** [comment]
> Hi I am on Plasma I have a dark theme installed :Breeze Dark I find that with that selected that streamdeck-ui automatically follows that theme. If dark it shows dark........ ...
> 
> ![streamdeckuiDark](https://user-images.githubusercontent.com/53057579/189914220-01ca47a5-3268-48e7-a2f6-bff14a6257e5.png)
> 
> HIH
> 
> -- Data

Must be a gnome issue then :-/

**Comment by My1** [comment]
is your gnome theme as a whole dark too?
although an override for light/dark might not be bad

**Comment by oparada1988** [comment]
> is your gnome theme as a whole dark too? although an override for light/dark might not be bad

Yeah my gnome theme is all dark. I use the Ubuntu yaru dark purple theme

**Comment by dodgyrabbit** [comment]
The light/dark mode switching doesn't appear to work on all desktop managers "out the box" with the UI library we use unfortunately. It has never worked for me on Ubuntu but possibly it works under others. Low priority thing to improve, PR's welcome.

**Comment by zen2** [comment]
I end up here because for the same issue.
I'm using a QT/Gnome independent desktop based on openbox.
My gnome dark theme is configured for GTK applications.
QT applications use correctly my dark theme by using env variable `QT_QPA_PLATFORMTHEME=qt5ct`
and have launched qt5ct to select the same theme used for GTK applications.
So all GTK and QT applications use the same theme but streamdeck is not.

**Comment by oparada1988** [comment]
New update has enable dark mode on Gnome. I will close this issue.

![Screenshot from 2023-02-28 07-59-44](https://user-images.githubusercontent.com/4031078/221860958-132357fa-4629-4a1f-9280-d87c7962f68b.png)
