### ISSUE TITLE
Multi-Line labels

### ISSUE THREAD

**Issue by My1** [timothycrosley/streamdeck-ui#264]
**Please describe the problem would like to solve**
Basically an option to be able to use muiltiple lines for the labels so a label with 2 words doesnt have to cut off

**Describe the solution you'd like**
the best solution might be a text area, although adding `\n` or similar into the line might be a workable option if known

**Comment by dodgyrabbit** [comment]
See #185. Also, a multiline text area is in the works too.

**Comment by My1** [comment]
oh sorry, I did try to search but didnt find this one (likely because it filters open as default)

workaround works, thanks

**Comment by dodgyrabbit** [comment]
No problem
