### ISSUE TITLE
Unable to install on Fedora 37

### ISSUE THREAD

**Issue by tdcam** [timothycrosley/streamdeck-ui#277]
I have installed all the prerequisite packages:

[thomas.cameron@case ~]$ sudo dnf install python3-pip python3-devel hidapi
Last metadata expiration check: 1:06:50 ago on Sun 27 Nov 2022 05:08:20 PM CST.
Package python3-pip-22.2.2-2.fc37.noarch is already installed.
Package python3-devel-3.11.0-1.fc37.x86_64 is already installed.
Package hidapi-0.12.0-2.fc37.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

Then when I try to install using pip3 install, I get this:

[thomas.cameron@case ~]$ pip3 install --user streamdeck_ui
Collecting streamdeck_ui
  Using cached streamdeck_ui-1.0.2-py3-none-any.whl (1.2 MB)
Collecting hidapi<0.8.0,>=0.7.99
  Using cached hidapi-0.7.99.post21.tar.gz (51 kB)
  Preparing metadata (setup.py) ... done
Collecting pillow<7.0,>=6.1
  Using cached Pillow-6.2.2.tar.gz (37.8 MB)
  Preparing metadata (setup.py) ... done
Collecting pynput<2.0,>=1.4
  Using cached pynput-1.7.6-py2.py3-none-any.whl (89 kB)
Collecting pyside2<6.0,>=5.13
  Using cached PySide2-5.13.2-5.13.2-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl (156.1 MB)
Collecting streamdeck<0.7.0,>=0.6.3
  Using cached streamdeck-0.6.3-py3-none-any.whl (24 kB)
Requirement already satisfied: setuptools>=19.0 in /usr/lib/python3.11/site-packages (from hidapi<0.8.0,>=0.7.99->streamdeck_ui) (62.6.0)
Requirement already satisfied: six in /usr/lib/python3.11/site-packages (from pynput<2.0,>=1.4->streamdeck_ui) (1.16.0)
Collecting evdev>=1.3
  Using cached evdev-1.6.0.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: python-xlib>=0.17 in /usr/lib/python3.11/site-packages (from pynput<2.0,>=1.4->streamdeck_ui) (0.31)
Collecting shiboken2==5.13.2
  Using cached shiboken2-5.13.2-5.13.2-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl (832 kB)
Using legacy 'setup.py install' for hidapi, since package 'wheel' is not installed.
Using legacy 'setup.py install' for pillow, since package 'wheel' is not installed.
Using legacy 'setup.py install' for evdev, since package 'wheel' is not installed.
Installing collected packages: streamdeck, shiboken2, evdev, pyside2, pillow, hidapi, pynput, streamdeck_ui
  Running setup.py install for evdev ... done
  Running setup.py install for pillow ... done
  Running setup.py install for hidapi ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for hidapi did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      /usr/lib/python3.11/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      WARNING: The wheel package is not available.
      running install
      /usr/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      cythoning hid.pyx to hid.c
      /tmp/pip-install-aqlgfmcb/hidapi_6cfd54cf3e354ae5844513b814851c2a/.eggs/Cython-0.29.32-py3.11-linux-x86_64.egg/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-aqlgfmcb/hidapi_6cfd54cf3e354ae5844513b814851c2a/hid.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      cythoning hidraw.pyx to hidraw.c
      /tmp/pip-install-aqlgfmcb/hidapi_6cfd54cf3e354ae5844513b814851c2a/.eggs/Cython-0.29.32-py3.11-linux-x86_64.egg/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-aqlgfmcb/hidapi_6cfd54cf3e354ae5844513b814851c2a/hidraw.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      building 'hid' extension
      creating build
      creating build/temp.linux-x86_64-cpython-311
      creating build/temp.linux-x86_64-cpython-311/hidapi
      creating build/temp.linux-x86_64-cpython-311/hidapi/libusb
      gcc -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Ihidapi/hidapi -I/usr/include/libusb-1.0 -I/usr/include/python3.11 -c hid.c -o build/temp.linux-x86_64-cpython-311/hid.o
      gcc -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Ihidapi/hidapi -I/usr/include/libusb-1.0 -I/usr/include/python3.11 -c hidapi/libusb/hid.c -o build/temp.linux-x86_64-cpython-311/hidapi/libusb/hid.o
      hidapi/libusb/hid.c:26: warning: "_GNU_SOURCE" redefined
         26 | #define _GNU_SOURCE /* needed for wcsdup() before glibc 2.10 */
            |
      <command-line>: note: this is the location of the previous definition
      hidapi/libusb/hid.c:47:10: fatal error: libusb.h: No such file or directory
         47 | #include <libusb.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/lib64/ccache/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> hidapi

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

Any pointers on how to make this work?

**Comment by sscheib-rh** [comment]
I was able to resolve the above error by installing `libusb1-devel.x86_64`. Unfortunately, this is leading to another error:
```
pip3 install streamdeck-ui --user
Collecting streamdeck-ui
  Using cached streamdeck_ui-1.0.2-py3-none-any.whl (1.2 MB)
Collecting hidapi<0.8.0,>=0.7.99
  Using cached hidapi-0.7.99.post21.tar.gz (51 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pillow<7.0,>=6.1 in ./.local/lib/python3.11/site-packages (from streamdeck-ui) (6.2.2)
Collecting pynput<2.0,>=1.4
  Using cached pynput-1.7.6-py2.py3-none-any.whl (89 kB)
Requirement already satisfied: pyside2<6.0,>=5.13 in ./.local/lib/python3.11/site-packages (from streamdeck-ui) (5.13.2)
Requirement already satisfied: streamdeck<0.7.0,>=0.6.3 in ./.local/lib/python3.11/site-packages (from streamdeck-ui) (0.6.3)
Requirement already satisfied: setuptools>=19.0 in /usr/lib/python3.11/site-packages (from hidapi<0.8.0,>=0.7.99->streamdeck-ui) (62.6.0)
Requirement already satisfied: six in /usr/lib/python3.11/site-packages (from pynput<2.0,>=1.4->streamdeck-ui) (1.16.0)
Requirement already satisfied: evdev>=1.3 in /usr/lib64/python3.11/site-packages (from pynput<2.0,>=1.4->streamdeck-ui) (1.6.0)
Requirement already satisfied: python-xlib>=0.17 in /usr/lib/python3.11/site-packages (from pynput<2.0,>=1.4->streamdeck-ui) (0.31)
Requirement already satisfied: shiboken2==5.13.2 in ./.local/lib/python3.11/site-packages (from pyside2<6.0,>=5.13->streamdeck-ui) (5.13.2)
Using legacy 'setup.py install' for hidapi, since package 'wheel' is not installed.
Installing collected packages: hidapi, pynput, streamdeck-ui
  Running setup.py install for hidapi ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for hidapi did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      /usr/lib/python3.11/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      WARNING: The wheel package is not available.
      running install
      /usr/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      cythoning hid.pyx to hid.c
      /tmp/pip-install-y45r54kk/hidapi_065b1aac58034a87aa5245d03f3ab444/.eggs/Cython-0.29.32-py3.11-linux-x86_64.egg/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-y45r54kk/hidapi_065b1aac58034a87aa5245d03f3ab444/hid.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      cythoning hidraw.pyx to hidraw.c
      /tmp/pip-install-y45r54kk/hidapi_065b1aac58034a87aa5245d03f3ab444/.eggs/Cython-0.29.32-py3.11-linux-x86_64.egg/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-y45r54kk/hidapi_065b1aac58034a87aa5245d03f3ab444/hidraw.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      building 'hid' extension
      creating build
      creating build/temp.linux-x86_64-cpython-311
      creating build/temp.linux-x86_64-cpython-311/hidapi
      creating build/temp.linux-x86_64-cpython-311/hidapi/libusb
      gcc -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Ihidapi/hidapi -I/usr/include/libusb-1.0 -I/usr/include/python3.11 -c hid.c -o build/temp.linux-x86_64-cpython-311/hid.o
      gcc -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Ihidapi/hidapi -I/usr/include/libusb-1.0 -I/usr/include/python3.11 -c hidapi/libusb/hid.c -o build/temp.linux-x86_64-cpython-311/hidapi/libusb/hid.o
      hidapi/libusb/hid.c:26: warning: "_GNU_SOURCE" redefined
         26 | #define _GNU_SOURCE /* needed for wcsdup() before glibc 2.10 */
            |
      <command-line>: note: this is the location of the previous definition
      creating build/lib.linux-x86_64-cpython-311
      gcc -shared -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -Wl,--build-id=sha1 -g -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -Wl,--build-id=sha1 -g build/temp.linux-x86_64-cpython-311/hid.o build/temp.linux-x86_64-cpython-311/hidapi/libusb/hid.o -L/usr/lib64 -lusb-1.0 -ludev -lrt -o build/lib.linux-x86_64-cpython-311/hid.cpython-311-x86_64-linux-gnu.so
      /usr/bin/ld: cannot find -ludev: No such file or directory
      collect2: error: ld returned 1 exit status
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> hidapi

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```
Any pointers are greatly appreciated.

**Comment by swedishmike** [comment]
I seem to recall that I ran into the same one and that I resolved it with installing 'libusb-1.0.0-dev'. Worth a try at least. One difference though, I'm on Ubuntu - but still....

One thing I noticed in your output is this: 

```
Collecting streamdeck-ui
  Using cached streamdeck_ui-1.0.2-py3-none-any.whl (1.2 MB)
```

That is a rather old version of the UI. I _think_ it chooses that since you, like me, are on Python 3.10 and the config says that it's only compatible with lower versions. There is a PR in place to fix this ( https://github.com/timothycrosley/streamdeck-ui/pull/274 ) .

**Comment by sclarkso** [comment]
According to my notes is what I did on F37:

$ sudo dnf install python3-devel libusb-devel libusbx-devel libudev-devel systemd-devel
$ sudo pip3 uninstall pillow
$ sudo dnf install libjpeg-turbo-devel zlib-devel libtiff-devel openjpeg2-devel freetype-devel \
        lcms2-devel libwebp-devel tcl-devel tk-devel harfbuzz-devel fribidi-devel libraqm-devel \
        libimagequant-devel libxcb-devel
$ pip3 install pillow --no-cache-dir
$ pip3 install --user streamdeck_ui

**Comment by tdcam** [comment]
sclarkso - I think you meant:

sudo dnf install python3-devel libusb1-devel libusbx-devel libudev-devel systemd-devel

There is no package called libusb-devel on F37.

Also, running pip3 under sudo threw an error:

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Are you sure you meant for us to remove Pillow from /usr/lib64/python3.11/site-packages/ ?

Thanks!

**Comment by sclarkso** [comment]
I have removed my commands as they were more of a guideline and I should have said that.  

On Fedora 37 here are the packages I have installed re: gcc and hidapi to get past the error you're getting above.  You will need other packages to get "text" working.

gcc.x86_64                                             12.2.1-4.fc37                           @updates                                       
gcc-gdb-plugin.x86_64                                  12.2.1-4.fc37                           @updates                                       
libgcc.x86_64                                          12.2.1-4.fc37                           @updates

hidapi.x86_64                                          0.12.0-2.fc37                           @fedora                                        
hidapi-devel.x86_64                                    0.12.0-2.fc37                           @fedora                                        
python3-hidapi.x86_64                                  0.12.0.post2-3.fc37                     @fedora

I haven't tried it personally, but there is also "boatswain" on flatpak.

**Comment by tdcam** [comment]
I was able to get it to install using the following commands, many thanks to sclarkso, above:

sudo dnf install python3-devel libusb1-devel libusbx-devel libudev-devel systemd-devel

sudo pip3 uninstall pillow # NOTE this erases the system installation of pillow

sudo dnf install libjpeg-turbo-devel zlib-devel libtiff-devel openjpeg2-devel freetype-devel

pip3 install pillow --no-cache-dir

pip3 install --user streamdeck_ui

I don't know if this will work for everyone, I just know that it worked on my system. Hopefully it helps others. Big thanks for sclarkso's advice.

**Comment by andersonid** [comment]
None of above solutions is working on my F37, X11... 
I also have tryied to update pyside2 and shiboken2  to 5.15 version. No success. 
Seems to be an issue related to version requirements of dependencies and python 3.11

**Comment by pblanton** [comment]
This worked for me. install these dependencies...

```
sudo dnf install python3-devel libusb1-devel libusbx-devel libudev-devel systemd-devel
```

The libusb*  libs are the key.

Then run the installer.

```
pip3 install streamdeck-ui --user
```

My new problem now that StreamDeck UI is installed on Fedora 37 is that none of the launcher buttons do anything. That's not completely true. When I create a new launcher button in the UI, and it shows up on the device, the button works exactly once. Then it never works again. I'ma create a new bug report for that.

**Comment by patrickhgh** [comment]
After upgrading Fedora 36 to 37 Streamdeck will not launch.

[pwoodard@pwoodard ~]$ streamdeck
Traceback (most recent call last):
  File "/home/pwoodard/.local/bin/streamdeck", line 8, in <module>
    sys.exit(start())
             ^^^^^^^
  File "/home/pwoodard/.local/lib/python3.11/site-packages/streamdeck_ui/gui.py", line 269, in start
    build_device(ui)
  File "/home/pwoodard/.local/lib/python3.11/site-packages/streamdeck_ui/gui.py", line 199, in build_device
    build_buttons(ui, page)
  File "/home/pwoodard/.local/lib/python3.11/site-packages/streamdeck_ui/gui.py", line 129, in build_buttons
    deck = api.get_deck(deck_id)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pwoodard/.local/lib/python3.11/site-packages/streamdeck_ui/api.py", line 133, in get_deck
    return {"type": decks[deck_id].deck_type(), "layout": decks[deck_id].key_layout()}
                    ~~~~~^^^^^^^^^
KeyError: None

**Comment by dodgyrabbit** [comment]
See https://github.com/timothycrosley/streamdeck-ui/issues/293#issuecomment-1442785329

A proper fix will also be posted, hopefully a new build soon.
