### ISSUE TITLE
ImportError: this platform is not supported

### ISSUE THREAD

**Issue by VortexAcherontic** [timothycrosley/streamdeck-ui#285]
**Describe the bug**
streamdeck_ui does not start

**To Reproduce**
Steps to reproduce the behaviour:
1. Install streamdeck_ui as per [guide](https://timothycrosley.github.io/streamdeck-ui/#manual-installation) (manual)
2. Launch
3. Does not show up

**Expected behavior**
UI to show up

**Log**
````
vortexacherontic@z004:~> streamdeck 
Traceback (most recent call last):
  File "/home/vortexacherontic/.local/bin/streamdeck", line 5, in <module>
    from streamdeck_ui.gui import start
  File "/home/vortexacherontic/.local/lib/python3.10/site-packages/streamdeck_ui/gui.py", line 11, in <module>
    from pynput import keyboard
  File "/home/vortexacherontic/.local/lib/python3.10/site-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/home/vortexacherontic/.local/lib/python3.10/site-packages/pynput/keyboard/__init__.py", line 31, in <module>
    backend = backend(__name__)
  File "/home/vortexacherontic/.local/lib/python3.10/site-packages/pynput/_util/__init__.py", line 76, in backend
    raise ImportError('this platform is not supported: {}'.format(
ImportError: this platform is not supported: ('failed to acquire X connection: Can\'t connect to display ":0": b\'Authorization required, but no authorization protocol specified\\n\'', DisplayConnectionError(':0', b'Authorization required, but no authorization protocol specified\n'))

Try one of the following resolutions:

 * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly
````

Running streamdeck_ui within distrobox (openSUSE Tumbleweed) gives also the same errors both running on X11 and Wayland.

**Operating system (please complete the following information)**
 - OS: openSUSE MicroOS 20221223
 - Desktop environment: Gnome 43.2 (Wayland)
 - Python version: Python 3.10

**Stream Deck Version**
 - IDK, the one with 15 buttons (5x3)

**Additional notes**
Other python 3.10 based GUI apps work just fine, namely: bottles.  
Other X11 only apps work fine: namely xclock  
streamdeck_ui does also not work if running Gnome in X11, same error as above.

**Comment by dodgyrabbit** [comment]
See https://github.com/timothycrosley/streamdeck-ui/issues/284#issuecomment-1374604563 as it may work for you

**Comment by dodgyrabbit** [comment]
Review https://timothycrosley.github.io/streamdeck-ui/docs/installation/opensuse/ and install 2.0.13.
