### ISSUE TITLE
New streamdeck model

### ISSUE THREAD

**Issue by s4dic** [timothycrosley/streamdeck-ui#286]
I have bought a new Streamdeck, I observed a new model code :

Please can you add this line to your guide when we need to edit this file /etc/udev/rules.d/70-streamdeck.rules:
`SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="008f", TAG+="uaccess"`

![0500380500](https://user-images.githubusercontent.com/42476966/209484675-de514a0b-7d1c-4593-861d-5c0c6b6d63c3.png)
the problem is that the code "008f" is not listed in the official documentation

**Comment by LinuxGamesTV** [comment]
It is. I have the same model and it works.

**Comment by dodgyrabbit** [comment]
Thanks @LinuxGamesTV - that is exactly right.
