### ISSUE TITLE
Anything entered into the "Text" field is rendered in black text on a black button in the UI, so you cannot see it.

### ISSUE THREAD

**Issue by pblanton** [timothycrosley/streamdeck-ui#294]
**Update:** It may not be a dark-mode issue. Apparently my UI isn't in dark-mode, but the display is just always black. in which case this is an issue that affects anyone.

**Please describe the problem would like to solve**
Anything entered into the text field is rendered in black text on a black button. The text does render on the device properly but in the UI you can't see which buttons have been programmed unless there is an associated image.

**Describe the solution you'd like**
Any "text" should be rendered on the the UI button in a complementary color so that you can see it.

In the attached images, on the top row, the third and fourth buttons are programmed with text only. You can see when the third button is selected it turns gray and you can see the black text, but on the fourth button you can see that the black text on the black (un-selected) button is not visible. this makes it hard to tell which buttons have been programmed without looking at the device itself.

![image](https://user-images.githubusercontent.com/1143649/210623025-7b42392f-b0c8-4ec6-ada6-8b9ad1655898.png)

And on the device...

![image](https://user-images.githubusercontent.com/1143649/210623305-da2038bd-f81f-4017-a15e-1f2ad7cc6440.png)

**Comment by dodgyrabbit** [comment]
From the screenshot you are running a very old version of streamdeck-ui.
Please look through this repo and the main readme and get the latest version.

Please provide additional details are per the original bug request template.

**Operating system (please complete the following information)**
 - OS: [e.g. Ubuntu 20.04, Arch 2022.02.01]
 - Desktop environment: [e.g. Gnome]
 - Python version [e.g. Python 3.9]

**Stream Deck Version**
 - Mini, Standard, Standard MK.2, XL

**Comment by dodgyrabbit** [comment]
Closing. Please try install the latest version. If you're still having trouble, please reopen the case with the details in the standard bug template.
