### ISSUE TITLE
Documentation links to scripts appear to be broken.

### ISSUE THREAD

**Issue by digitalsparky** [timothycrosley/streamdeck-ui#296]
**Describe the bug**
There appears to be a bug/configuration issue related to the linking and processing of script files.
In this particular case, the scripts linked in precooked-scripts throw a very broken 404, despite the scripts actually existing and being linked to properly in the source doco. One could assume that either the .sh files aren't being ignored and uploaded as standard script files, or there is a linking issue.

Essentially, this means the documentation is buggy and could make it a lot harder for people to get started.

**To Reproduce**
1. Go to https://timothycrosley.github.io/streamdeck-ui/#precooked-scripts
2. Click on either the Ubuntu or Fedora script
3. See a 404 error and broken page.

**Expected behavior**
I would expect my browser to download the shell script as linked, as opposed to a 404/broken page.

**Screenshots**
N/A

**Operating system (please complete the following information)**
N/A (browser based documentation)

**Stream Deck Version**
N/A

**Comment by dodgyrabbit** [comment]
Thanks for reporting this. I figured out how to update the gh-pages. The links should be good now, and the outdated documentation has been rebuilt too.

**Comment by digitalsparky** [comment]
Thanks @dodgyrabbit - much appreciated. Have an awesome week!
