### ISSUE TITLE
Add rule for Stream Deck Mini to the guide

### ISSUE THREAD

**Issue by saldang** [timothycrosley/streamdeck-ui#297]
**Describe the bug**
Following the manual installation [https://timothycrosley.github.io/streamdeck-ui/](https://timothycrosley.github.io/streamdeck-ui/) from the guide the Stream Deck mini is not accessible.

**To Reproduce**
1. sudo apt install python3-pip libhidapi-libusb0 libxcb-xinerama0
2. sudo nano /etc/udev/rules.d/70-streamdeck.rules
3. 
```
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0063", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006c", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006d", TAG+="uaccess"
```

**Screenshots**
![image](https://user-images.githubusercontent.com/92312624/212279615-a5678b8a-45e9-4fb0-844a-ee0b93459088.png)

**Operating system (please complete the following information)**
 - OS: PopOS 22.04
 - Desktop environment: Gnome
 - Python version: Python 3.9 Anaconda

**Stream Deck Version**
 - Mini

To fix the guide just add the following line:
```SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0090", TAG+="uaccess"```

**Comment by LinuxGamesTV** [comment]
Why?

`SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", TAG+="uaccess"`

This is the rule for all Elgato devices.

This mean you don't need the entry:

`, ATTRS{idProduct}=="006d*`

**Comment by saldang** [comment]
I agree with you but [here](https://timothycrosley.github.io/streamdeck-ui/) I think that can be updated

**Comment by dodgyrabbit** [comment]
Thanks, the documentation has been updated.
