### ISSUE TITLE
No Text / Image being set on Stream Deck XL, GUI not responding

### ISSUE THREAD

**Issue by xorbital** [timothycrosley/streamdeck-ui#3]
First of all, thanks for your great work.

I've installed the application as described on Manjaro as well as on Pop!OS (basically Ubuntu), but haven't had any luck setting images or text.

Changing the brightness works fine, however as soon as I interact with basically any UI element (clicking a button or one of the text fields, entering text, choosing an image, ...) the application freezes for about 40 seconds.
The same is happening when starting, after entering "streamdeck", I usually have to wait 40-60s.
After that the action is being executed (Button / Field selected / Text entered).
Setting a command works, for example a zenity popup opens, entering text works as well.

However setting an image results in the Stream Deck staying black, the same is true for setting a text.

Trying the examples from the library resulted in similar behavior, setting an image doesn't work there either, the only example working is example_deckinfo.py.

Anything I might have missed?
Even after installing with the script and playing around with the udev rule the deck doesn't display anything other than different shades of black depending on the brightness.

Hardware: Two entirely different computers, Stream Deck XL
OS: Manjaro and Pop!OS (as well as Ubuntu in a VM)
Firmware version of the deck: 1.00.006

Next thing I'm gonna try is attaching it to a Windows 10 VM, however using this application would obviously be a lot better.

UPDATE: Using the Windows VM works perfectly fine, no problems. Seems like there's no firmware update available.

**Comment by xorbital** [comment]
So, after playing around a little more, I've found the node.js-Library to be working fine.
Tried the python one and the UI on another Kubuntu machine, still nothing, no errors being thrown either.
Any debugging options I could enable?

**Comment by timothycrosley** [comment]
Sorry to hear this! I was afraid this could happen, since I don't have an XL to test with, I only have the standard 15 key model. I was relying on the stated support within the Python library, but it's likely the maintainer of that library also doesn't have an XL available and was hopeful that a contributor's patch would add access - without a direct way to test it. I'll try to get my hands on an XL model for testing soon, and see If I can't fix whatever is going on with the display for that model.

Thanks,

~Timothy

**Comment by xorbital** [comment]
The upstream bug of the library has been resolved, the UI now works :tada:
Weird thing is that the UI forces an install of the streamdeck library version 0.5.x while the XL only works with 0.6.3
