### ISSUE TITLE
Version 2.0.13 released

### ISSUE THREAD

**Issue by dodgyrabbit** [timothycrosley/streamdeck-ui#300]
Hi everyone,

It's been a while since I gave this project some much needed attention. My goal was simple: get it working on some of the newer Operating Systems. The main culprit is that OS's are now running Python 3.11 by default, which is incompatible with streamdeck-ui's requirements. However, the dependency on PySide2 (required Python <= 3.10) made this impossible to solve. So the latest release switches to PySide6 to resolve this.

The python-xlib library (required by pynput) also got updated, which a voids a few unecessary problems. Unfortunately this does not mean that the keyboard emulation will work under Wayland. However, the streamdeck-ui should now _launch_ without problems. If there is a good way to detect Wayland, I'll hide/disable these features it in future.

I added some messaging on startup to help with a couple of common installation problems.

The [documentation site](https://timothycrosley.github.io/streamdeck-ui/) has finally been updated. It was the cause of much frustration because people find that via Google and it had _way_ outdated instructions.

In addition, I updated the installation guides for many Linux versions and tested them all.

You can upgrade an existing installation as follows:
```
python -m pip install streamdeck-ui --user --upgrade
```
The once-off upgrade to PySide6 may take a while.

https://github.com/timothycrosley/streamdeck-ui/blob/master/CHANGELOG.md#2013---27-feb-2023

**Comment by oparada1988** [comment]
Thanks for the new release! I was surprise to see the dark mode working on Gnome! Thanks again!

**Comment by tristengrant** [comment]
Will there be websocket integration?

**Comment by oparada1988** [comment]
> Will there be websocket integration?

If this is in regards to OBS I use the following tool, https://github.com/muesli/obs-cli

Perhaps this could be intergrated to Streamdeck UI in the future.

**Comment by tristengrant** [comment]
> > Will there be websocket integration?
> 
> If this is in regards to OBS I use the following tool, https://github.com/muesli/obs-cli
> 
> Perhaps this could be intergrated to Streamdeck UI in the future.

OBS CLI worked perfectly. Thank you!
