### ISSUE TITLE
Probable error in terminal output

### ISSUE THREAD

**Issue by linux-lukas** [timothycrosley/streamdeck-ui#305]
**Describe the bug**
When pressing a button configured with Thunderbird, presumably errors occur.

**To Reproduce**
1. Configure a python3 virtual env 
1. Configure the following action 'Set button with "thunderbird" as command'.
2. Press "thunderbird" button 
4. Review console output
5. See error

```
[ImapModuleLoader] Using nsImapService.cpp

[NntpModuleLoader] Using NntpService.jsm

[Pop3ModuleLoader] Using Pop3Service.jsm

ATTENTION: default value of option mesa_glthread overridden by environment.

ATTENTION: default value of option mesa_glthread overridden by environment.

ATTENTION: default value of option mesa_glthread overridden by environment.

ATTENTION: default value of option mesa_glthread overridden by environment.

[calBackendLoader] Using Thunderbird's ical.js backend

console.debug: "Successfully loaded OpenPGP library librnp.so version 0.16.2+git20220922.298ad98b.MZLA from 
/usr/lib/thunderbird/librnp.so"

console.debug: "Found X public keys and x secret keys (x protected, 0 unprotected)"

console.debug: "Successfully loaded optional OpenPGP library libgpgme.so.11 from system's standard library locations"

console.debug: "gpgme version: 1.13.1-unknown"

console.warn: services.settings: Failed to load last_modified.json: TypeError: NetworkError when attempting to fetch resource.

console.log: WebExtensions: no migration

console.debug: "Trying to load /usr/lib/thunderbird/libotr.so"

console.debug: "Trying to load libotr.so from system's standard library locations"

console.debug: "Trying to load libotr.so.5 from system's standard library locations"

console.debug: "Trying to load libotr.so from system's standard library locations"

console.log: (new Error("Cannot load required OTR library", "resource:///modules/OTRLib.jsm", 109))

```

**Expected behavior**

No error display in the CMD

**Screenshots**

**Operating system (please complete the following information)**
 - OS: Ubuntu 20.04.05 LTS
 - Desktop environment: Gnome 3.36.8
 - Python version: Python 3.8.10
 - Pip version: pip 22.1.2

**Stream Deck Version**
- Stream Deck MK.2

**Comment by dodgyrabbit** [comment]
These errors are not coming from this application. Presumably you've done troubleshooting, like confirming that with `which thunderbird` produces a valid path and also that running `thunderbird` from the terminal does not have any errors.  

Quick google may point you in a direction:
https://bugzilla.mozilla.org/show_bug.cgi?id=1703824
