### ISSUE TITLE
Switching Workspaces

### ISSUE THREAD

**Issue by justbenuk** [timothycrosley/streamdeck-ui#309]
I like to use my streamdeck to switch workspaces, My current keymaps are Super(1 to 5). if I press them on my keyboard all works as expected. If I press them on the streamdeck it opens the activities window (same as when you press just the super key)

I have set the streamdeck to press cmd+1 to change to workspace space one. But it just opens the activities window instead of moving to workspace 1
**Expected behavior**

I am currently running Manjaro Gnome 

My streamdeck is the MK.2, XL

**Comment by oparada1988** [comment]
Have you tried using xev to determine the key keysym number? for super+1 should be:

0xffe9+0x31

for super+1(numpad)

0xffe9+0xffb1

**Comment by keilmillerjr** [comment]
I can confirm this issue. `cmd+2` and `cmd+0x32` (using xev) both yield only a super keypress. Can we re-open this issue?

Using the streamdeck-ui package 2.0.15-1 (latest git commit).

```
System:
  Kernel: 6.2.9-arch1-1 arch: x86_64 bits: 64 compiler: gcc v: 12.2.1
  Desktop: GNOME v: 43.4 tk: GTK v: 3.24.37 wm: gnome-shell dm: GDM v: 43.0
    Distro: Arch Linux
```

**Comment by keilmillerjr** [comment]
A workaround is using the xdotool utility.

command: `xdotool key super+2`
