### ISSUE TITLE
Not launching error

### ISSUE THREAD

**Issue by PixelRave** [timothycrosley/streamdeck-ui#313]
**Describe the bug**
Streamdeck UI will not launch. Even on a clean install. I have followed all instructions on the fedora install page. And this is running the latest version.

**To Reproduce**

1. type streamdeck into command prompt
2. Interface pops up
3. I get this error...

 _*** Problem detected ***
A Stream Deck is attached, but it could not be opened.
Check installation instructions and ensure a udev rule has been added and loaded._

**Expected behavior**
For the program to launch properly.

**Operating system (please complete the following information)**
 - Fedora (Nobara)
 - Gnome
 - Python 3.11.2
 - Wayland

**Stream Deck Version**
 - Mini

**Comment by Data-007** [comment]
https://github.com/timothycrosley/streamdeck-ui/blob/master/docs/installation/fedora.md

See section on making udv rules.

I hope that fixes it for you

--

Data- 007

**Comment by heavyironbull** [comment]
I am having a similar issue with my MK.2, but on Arch. I have the udev rule created.  

I do see this in the journal.  These lines show up every second:

Mar 31 13:32:50 localhost kernel: input: Elgato Stream Deck MK.2 as /devices/pci0000:00/0000:00:14.0/usb1/1-9/1-9.3/1-9.3.2/1-9.3.2.1/1-9.3.2.1.3/1-9.3.2.1.3:1.0/0003:0FD9:0080.0197/input/input425
Mar 31 13:32:50 localhost kernel: hid-generic 0003:0FD9:0080.0197: input,hidraw7: USB HID v1.10 Device [Elgato Stream Deck MK.2] on usb-0000:00:14.0-9.3.2.1.3/input0
Mar 31 13:32:50 localhost systemd-logind[706]: Failed to open /dev/input/event11: No such file or directory
Mar 31 13:32:50 localhost /usr/libexec/gdm-x-session[1974]: (II) config/udev: Adding input device (unnamed) (/dev/input/event11)
Mar 31 13:32:50 localhost /usr/libexec/gdm-x-session[1974]: (**) (unnamed): Applying InputClass "libinput keyboard catchall"
Mar 31 13:32:50 localhost /usr/libexec/gdm-x-session[1974]: (II) Using input driver 'libinput' for '(unnamed)'
Mar 31 13:32:50 localhost /usr/libexec/gdm-x-session[1974]: (EE) systemd-logind: failed to take device /dev/input/event11: No such device
Mar 31 13:32:50 localhost /usr/libexec/gdm-x-session[1974]: (**) (unnamed): always reports core events
Mar 31 13:32:50 localhost /usr/libexec/gdm-x-session[1974]: (**) Option "Device" "/dev/input/event11"
Mar 31 13:32:50 localhost /usr/libexec/gdm-x-session[1974]: (EE) client bug: Invalid path /dev/input/event11
Mar 31 13:32:50 localhost /usr/libexec/gdm-x-session[1974]: (EE) libinput: (unnamed): Failed to create a device for /dev/input/event11
Mar 31 13:32:50 localhost /usr/libexec/gdm-x-session[1974]: (EE) PreInit returned 2 for "(unnamed)"
Mar 31 13:32:50 localhost /usr/libexec/gdm-x-session[1974]: (II) UnloadModule: "libinput"

$ cat /etc/udev/rules.d/70-streamdeck.rules
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", TAG+="uaccess"
$

$ streamdeck

------------------------
*** Problem detected ***
------------------------
A Stream Deck is attached, but it could not be opened.
Check installation instructions and ensure a udev rule has been added and loaded.
https://github.com/timothycrosley/streamdeck-ui

**Comment by Data-007** [comment]
Hi I am just an outside user like yourselves.
There is on Arch a package for streamdeck in/on aur 


streamdeck-ui | 2.0.15-1 | 3 | 0.01 | A Linux compatible UI for the Elgato Stream Deck
[streamdeck-ui ](https://aur.archlinux.org/packages/streamdeck-ui)	2.0.15-1 	3 	0.01 	A Linux compatible UI for the Elgato Stream Deck

For Arch its what I use now its as you can see the same as the pip version this may help you maybe not.
All I know is it works for me.
HIH

--

Data007
