### ISSUE TITLE
Relative os paths (~) for icons

### ISSUE THREAD

**Issue by NoUselessTech** [timothycrosley/streamdeck-ui#317]
**Please describe the problem would like to solve**
I would like to distribute my themes and icons without having an absolute path stored in the json with my home directory. When I tried to use a relative path (~/Pictures) this created an issue where the icons were not loaded.

**Describe the solution you'd like**
When files are added to the json with a relative path to the user homedir (~) this is expanded for inclusion in the stream deck outcomes.

**Comment by NoUselessTech** [comment]
Working on this.

**Comment by dodgyrabbit** [comment]
Merged for next release
