### ISSUE TITLE
ubuntu 18.04 requires libusb-1.0-0-dev package

### ISSUE THREAD

**Issue by ianfloats** [timothycrosley/streamdeck-ui#321]
**Describe the bug**
Following the instructions for ubuntu, compilation fails due to missing libusb.h

> hidapi/libusb/hid.c:47:10: fatal error: libusb.h: No such file or directory

**Operating system (please complete the following information)**
 - OS: Ubuntu 18.04

apt-get installing libusb-1.0-0-dev fixed it

**Comment by IanWorrall** [comment]
Ubuntu will no longer support 18.04 after 30th April 2023, that's only 2 weeks from today.
Maybe consider updating your OS?

**Comment by ianfloats** [comment]
Yes, will do, just noting it here in case others have the issue.

Thanks for this project!
