### ISSUE TITLE
Fresh install on Fedora 38, Streamdeck-ui fails to launch

### ISSUE THREAD

**Issue by tdcam** [timothycrosley/streamdeck-ui#329]
What I did:

sudo dnf install python3-pip python3-devel hidapi
python -m pip install --upgrade pip
sudo sh -c 'echo "SUBSYSTEM==\"usb\", ATTRS{idVendor}==\"0fd9\", TAG+=\"uaccess\"" > /etc/udev/rules.d/70-streamdeck.rules'
sudo udevadm trigger
python -m pip install streamdeck-ui --user
[thomas.cameron@host167 Desktop]$ streamdeck
Traceback (most recent call last):
  File "/home/thomas.cameron/.local/bin/streamdeck", line 5, in <module>
    from streamdeck_ui.gui import start
  File "/home/thomas.cameron/.local/lib/python3.11/site-packages/streamdeck_ui/gui.py", line 17, in <module>
    from streamdeck_ui.api import StreamDeckServer
  File "/home/thomas.cameron/.local/lib/python3.11/site-packages/streamdeck_ui/api.py", line 8, in <module>
    from PIL.ImageQt import ImageQt
ModuleNotFoundError: No module named 'PIL.ImageQt'

**Comment by tdcam** [comment]
OK, dug around, saw that I might need to install python3-pillow-qt. I did that, and now the error is:

[thomas.cameron@host167 Desktop]$ streamdeck
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.

**Comment by dodgyrabbit** [comment]
Have a look at https://github.com/timothycrosley/streamdeck-ui/issues/328

**Comment by tdcam** [comment]
OK, so in order to fix this, I did two things:

pip install pillow --upgrade
sudo dnf install xcb-util-cursor

Once I did both of those, streamdeck started working.

Thanks!
