### ISSUE TITLE
program does not launch after installing

### ISSUE THREAD

**Issue by EWeapon** [timothycrosley/streamdeck-ui#330]
**Describe the bug**
After installing the program  ether using the terminal command "Streamdeck" or clicking on the program icon will fail to launch.
Terminal will sit on "looking for streamdeck(s)...", program icon will launch an icon on the task bar with a loading wheel for about 2 seconds before closing

No errors are presented at any point, not sure where to move from here, any assistance or insight would be appreciated

Thank you.

**Operating system (please complete the following information)**
 - OS: Ubuntu 23.04
 - Desktop environment: Kubuntu
 - Python version: 3.11.2
![streamdeck error](https://user-images.githubusercontent.com/125173562/235711325-626b3151-578a-4323-a0ae-bdad8e3f4992.png)

**Stream Deck Version**
 - 15 key classic model # 20GAA9902

**Comment by dodgyrabbit** [comment]
Can you describe how you went about installing?
From the screenshot it appears that you are running an old version.

Not saying it will fix your problem to upgrade, but let's start there.

The basic Ubuntu install instructions is here:
https://timothycrosley.github.io/streamdeck-ui/docs/installation/ubuntu/
https://timothycrosley.github.io/streamdeck-ui/docs/troubleshooting/

There are some challenges with  Ubuntu 23.04, search the forum for some examples. You should be installing it in a virtual environment (this requirement is new in 23.04).

**Comment by EWeapon** [comment]
So i started at step one on your instruction's by installing hidapi 

Then eddited the .bashrc to add the path location stated
![bashrc](https://user-images.githubusercontent.com/125173562/235906324-011a95db-415f-40af-a818-23d6bd43a474.jpg)

Then ran the command to create the streamdeck rules file
![streamdeckrules](https://user-images.githubusercontent.com/125173562/235906365-2215a195-c5c4-4c6e-b172-48274a28d9f4.png)

Ran the trigger (funny side story, this command fixed my audio card)

Created the virtual environment and was presented with the following error
![virtual env](https://user-images.githubusercontent.com/125173562/235906663-0f15834d-c64b-4dbf-852b-5419e0877097.png)

I then hit up google for ideas and was eventually (you are probably gonna hate me for this) lead to a .deb that was put together at 
https://ubuntu.pkgs.org/22.04/ubuntu-universe-arm64/streamdeck-ui_1.1.2-2_all.deb.html

after running that deb is where i sit now, no further errors but no functionality

thank you again for your time, and im sorry for any frustrations i have caused in detouring from instruction

**Comment by EWeapon** [comment]
Thank you very much djnrrd, that got me past that spot, however continuing the install from there resulted in a permissions error (error 13), im not sure why i don't have perms for an environment i just made, any ideas on that?
![Permissions error 13](https://github.com/timothycrosley/streamdeck-ui/assets/125173562/f7763db9-f3aa-4b8d-be14-468fc021ddae)

**Comment by djnrrd** [comment]
Hmm, that's an odd one, but at least you are dealing with an OS layer issue now, and not a Python or streamdeck-ui issue.  Looks like you're going to need to do a bunch of fudging with `ls -al` `chown` and `chmod`

**Comment by EWeapon** [comment]
Thank you very much!.
 I was able to get permission's on the folder by chomod -R on the directory and can run the application now.
Two question's
 since i had to install this on a virtual environment do i need to activate the enviroment each time i wish to use the stream deck? might be a good idea to make a shell script for it then.
and would the environment effect detecting the device, as it stands now it still does not see it

again i seriously appreciate the help so far, thank you

**Comment by djnrrd** [comment]
> since i had to install this on a virtual environment do i need to activate the enviroment each time i wish to use the stream deck? might be a good idea to make a shell script for it then.

Correct, I'll be doing the same after I fix all the scripts my streamdeck calls

> and would the environment effect detecting the device, as it stands now it still does not see it

Hmm, it shouldn't. Python environments are really just about updating paths so that the environment is preferred and you can silo your required libraries. You should still have access to the rest of the file system and it's hardware.  Double check the instructions that you've got all the right libraries, and have done all the udev related bits.  Otherwise I'm stumped, I was only here today to try and resolve my own issues, but glad I could help you move further with yours :)
