### ISSUE TITLE
Feature request: config reset

### ISSUE THREAD

**Issue by tejasraman** [timothycrosley/streamdeck-ui#333]
**Please describe the problem would like to solve**
I would like be able to reset my StreamdeckUI config from within the app

**Describe the solution you'd like**
A reset button provided in menu (under "file"??)

**Comment by 4s3ti** [comment]
hi, this project seems to be stale and a new fork as been made with the intention of replacing this one.

if this still an issue please reopen it at: https://github.com/streamdeck-linux-gui/streamdeck-linux-gui

**Comment by tejasraman** [comment]
> hi, this project seems to be stale and a new fork as been made with the intention of replacing this one.
> 
> if this still an issue please reopen it at: https://github.com/streamdeck-linux-gui/streamdeck-linux-gui

Tysmmmm!

**Comment by 4s3ti** [comment]
how are you finding bitfocus? I find the documentation on it a bit .... terrible xD but in fairness haven't looked much into it.  might give it a ride one day.

**Comment by tejasraman** [comment]
> how are you finding bitfocus? I find the documentation on it a bit .... terrible xD but in fairness haven't looked much into it.  might give it a ride one day.

The docs are utterly horrific for companion, but here are the steps: make an account, download it (get the 2 beta),  change some udev rules (even on systemd >150), and run it. Then it should work
