### ISSUE TITLE
A suitable LibUSB installation could not be found.

### ISSUE THREAD

**Issue by dbozec** [timothycrosley/streamdeck-ui#358]
**Describe the bug**
Get the message "A suitable LibUSB installation could not be found." after the application starts, and unable to configure anything in the app, 
The app only respond when clicking on pages tabs and on menu

**To Reproduce**
1. Install streamdeck-ui following Ubuntu install procedure
2. start streamdeck in console : ```$ streamdeck```
3. Got following output :
```
------------------------
*** Problem detected ***
------------------------
A suitable LibUSB installation could not be found.
Check installation instructions:
https://github.com/timothycrosley/streamdeck-ui
```

libusb-1.0-0 and libusb-1.0-0-dev are installed

**Expected behavior**
Application start without error

**Operating system (please complete the following information)**
 - OS: Ubuntu 22.04.3 LTS
 - Desktop environment: Openbox
 - Python version : Python 3.10.12
 - streamdeck 0.9.4
 - pyside6 6.5.2
 - pilow 9.5.0
 - pynput 1.7.6

**Stream Deck Version**
 - Standard MK.2

**Comment by blu3bird** [comment]
The error message shown is a bit vague. You need "libhidapi-libusb.so.0", which is part of libusb but is typically provided under it's own name: libhidapi or sometimes libhidapi-libusb

For Ubuntu this snippet should work:
```
apt-get install libhidapi-libusb0
ln -sf libhidapi-libusb.so.0.0.0 /usr/lib/x86_64-linux-gnu/libhidapi-libusb.so.0
```

**Comment by dbozec** [comment]
libhidapi-libusb0 is already installed and the symbolic link already exists too

**Comment by stu** [comment]
I'm seeing this as well and satisfy the conditions;


````
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"

dpkg -l|grep libusb-1.0
ii  libusb-1.0-0:amd64            2:1.0.25-1ubuntu2                amd64        userspace USB programming library
ii  libusb-1.0-0-dev:amd64        2:1.0.25-1ubuntu2                amd64        userspace USB programming library development files

dpkg -l|grep libhidapi-libusb
ii  libhidapi-libusb0:amd64       0.11.2-1                         amd64        Multi-Platform library for communication with HID devices (libusb backend)

ls -ls /usr/lib/x86_64-linux-gnu/libhidapi-libusb*
32K -rw-r--r-- 1 root root 32K Feb 14  2022 /usr/lib/x86_64-linux-gnu/libhidapi-libusb.a
  0 lrwxrwxrwx 1 root root  25 Feb 14  2022 /usr/lib/x86_64-linux-gnu/libhidapi-libusb.so -> libhidapi-libusb.so.0.0.0
  0 lrwxrwxrwx 1 root root  25 Feb 14  2022 /usr/lib/x86_64-linux-gnu/libhidapi-libusb.so.0 -> libhidapi-libusb.so.0.0.0
44K -rw-r--r-- 1 root root 42K Feb 14  2022 /usr/lib/x86_64-linux-gnu/libhidapi-libusb.so.0.0.0
````


what I did to fix things, was run 

`pip-review --user -a `
which updated a bunch of python stuff, complained about a streamdeck ui
`streamdeck-ui 2.0.15 requires pillow<10.0.0,>=9.4.0, but you have pillow 10.2.0 which is incompatible`

so I redid a local virtualenv
`poetry config virtualenvs.create true`
then re-ran
`pip3 install --user streamdeck_ui`

and now it works again.

**Comment by dbozec** [comment]
Thank you !
It works perfectly for me too now !
