### ISSUE TITLE
Thread hangs when calling _key_change_callback

### ISSUE THREAD

**Issue by dx9s** [timothycrosley/streamdeck-ui#39]
https://github.com/timothycrosley/streamdeck-ui/blob/9b6678d2d3027963ddac147ee3aeda322ec77f29/streamdeck_ui/api.py#L33

I added some print statements before and after the keyboard.press/release code:

`        if keys:

            print("Into if keys:")

            keys = keys.strip().replace(" ", "")

            for section in keys.split(","):

                for key_name in section.split("+"):

                    keyboard.press(getattr(Key, key_name.lower(), key_name))

                for key_name in section.split("+"):

                    keyboard.release(getattr(Key, key_name.lower(), key_name))

            print("Outof if keys:")`

(running from terminal window) have to control+\ to terminate the entire app, if I press a key I know to have a bad hotkey in it: (first button is good, second button is known bad)

$ streamdeck 
Into if keys:
Outof if keys:
Into if keys:
^\Quit (core dumped)

Tried to read the code/documentation and I am just don't see anything good here: https://github.com/boppreh/keyboard/blob/master/keyboard/__init__.py#L394 

Be nice to put some try/catch or whatever would work here and prevent the worker thread from hanging (the gui thread is uneffected).

--Doug (dx9s)

**Comment by dx9s** [comment]
Forked and created a possible solution for bad hotkeys (what they are called in the python keyboard library): 

https://github.com/timothycrosley/streamdeck-ui/pull/40

**Comment by dodgyrabbit** [comment]
This has been fixed and will be available in 1.0.3
