### ISSUE TITLE
Is it supports StreamDeck on the mobile devices? Android, iOS apps.

### ISSUE THREAD

**Issue by RIP21** [timothycrosley/streamdeck-ui#42]
I'm getting the following issue after installation and I assume because I don't have any physical StreamDecks.
![image](https://user-images.githubusercontent.com/3940079/78717853-8a561380-7921-11ea-9a12-5a4271cdcd29.png)
Some meaningful error message here would help :D But I can guess by code that reason is exactly that :P
Hope someday it will support that :)

**Comment by sftim** [comment]
The mobile apps are quite different from the physical Stream Deck devices. I think it would be a great deal of work to make this tool also compatible with ElGato's proprietary smartphone apps.

Unlike the mobile apps, the physical devices implement USB HID and so are _fairly_ easy to code drivers for etc.

**Comment by dodgyrabbit** [comment]
There is a PR in the pipeline to give a more meaningful message while waiting for a SD to be attached.
