### ISSUE TITLE
Lock streamdeck when session locked

### ISSUE THREAD

**Issue by sftim** [timothycrosley/streamdeck-ui#46]
As a security-conscious user, I want the Stream Deck to lock (dim the screen and not respond to button pushes) whenever my session is locked.

Relevant to issues #4 and #7

**Comment by gytisrepecka** [comment]
That would be a great option 👍 Buttons could turn into grayed-out lock symbols (or show some picture in Wallpaper Mode) and most important - Stream Deck would not perform assigned commands.

Anyone has some quick pointers? I hope it would not require cycle through all pages and buttons within them to implement.

**Comment by sftim** [comment]
Logging the issue was easy :wink:
Other than seeing that it uses Python and relies on a library, I haven't looked at what this task could involve. I imagine that interacting with `logind` would work best.

(a work-around: if you have a security sensitive command, you can run a wrapper tool that only performs the command if your session is active)

**Comment by sftim** [comment]
I did notice that https://github.com/timothycrosley/streamdeck-ui/pull/73 lays some groundwork for this by allowing dynamic drawing (for example, to show a locked / unlocked padlock for a session lock button).

Subscribing to the `Lock` signal from [org.freedesktop.login1](https://www.freedesktop.org/software/systemd/man/org.freedesktop.login1.html#) might be useful too.

**Comment by DavidFromNL** [comment]
Thanks for importing #103 in here.
As mentioned in #103 I'd like to suggest a checkbox per configured button to allow using it when locked. Of course this should be disabled by default. But having such a checkbox would allow some actions to still be used when locked. For example: switching domotica or muting your music

**Comment by sftim** [comment]
If anyone wants help on the overall design for how this could work / where to subscribe to session lock events / etc, I can help. I don't think I'd have the time to look at the coding side though sorry.

**Comment by flajann2** [comment]
While we're at it, it would also be nice if Streamdeck-ui could work as exected across multiple simultaneous sessions. For example, I typically have a work session and a gaming session running -- for security reasons. When in the gaming session, Streamdeck-ui is still active in the work session. It should either shut down / stop accepting input when the gaming session is active, OR allow me to run a completey separate instance of Streamdeck-ui  there!

**Comment by sftim** [comment]
@flajann2 I can help design what you suggest but I don't have anywhere near enough time to spare to make it happen.
If you open a new issue for that request, mention https://github.com/timothycrosley/streamdeck-ui/issues/46#issuecomment-904358422 and I'll fill in some details.

**Comment by 4s3ti** [comment]
hi, this project seems to be stale and a new fork as been made with the intention of replacing this one.

if this still an issue please reopen it at: https://github.com/streamdeck-linux-gui/streamdeck-linux-gui

**Comment by sftim** [comment]
There's no obvious way to open an issue.

**Comment by 4s3ti** [comment]
Apologies. 

Fixed now. 

however I believe the better suited place for this is [here](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/discussions/categories/ideas-feature-requets) as this is not really an issue or a bug and more like a new feature tied to physsical security concerns.  some users (like myself) might actually want it to work when the screen is locked  :)

**Comment by DavidFromNL** [comment]
I see the benefit of (some) streamdeck functions working when the screen is locked. I myself toggle several external devices using my streamdeck. But this option should not be the default. It could compromise security.
I would suggest blocking the streamdeck functions by default when the screen is locked, just allowing the use of the buttons which were marked with a checkbox "allow when screen is locked".

**Comment by 4s3ti** [comment]
yup agreed 100% 

Please open up the discussion feature request in the discussions so it can be taken further in he new repository. I'm probably not the one going to do any code related to it, but maybe there will be someone interested in picking it up.

**Comment by sftim** [comment]
Please see https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/discussions/15
