### ISSUE TITLE
Animated Icons

### ISSUE THREAD

**Issue by lennartkoopmann** [timothycrosley/streamdeck-ui#50]
First of all, thank you for writing this fantastic piece of software. I really enjoy using it.

It seems like the Stream Deck supports `.gif` files for animated icons. Having support for this in `streamdeck-ui` would be really nice. I'm happy to at least help test this, but might find some time to work on this, too.

**Comment by Kitsune-Kuro** [comment]
I'm work on it.

**Comment by dodgyrabbit** [comment]
Ready for test in #206
