### ISSUE TITLE
JPEG compression artefacts in button images

### ISSUE THREAD

**Issue by n-st** [timothycrosley/streamdeck-ui#52]
I'll just quote the [upstream issue](https://github.com/abcminiuser/python-elgato-streamdeck/issues/35#issue-562019362) since I'm observing the same thing:
> The image quality on my StreamDeck original V2 is quite poor. This is especially noticeable when having intense colors, e.g. red text on black background.

After digging around a bit, I found that this issue has already been reported — and indeed fixed — in the library used to control the StreamDeck: abcminiuser/python-elgato-streamdeck#35

The [fix (explicitly setting the JPEG quality to 100)](https://github.com/abcminiuser/python-elgato-streamdeck/commit/ec9180c6d85db255bd0fe5aec09588996d5cee61) is included in `streamdeck` versions 0.7.0 and higher.

Would it be possible to update `streamdeck-ui`'s dependency accordingly to pull in the fix?

**Comment by dodgyrabbit** [comment]
This will be fixed in an upcoming release, when the related streamdeck-ui dependency is updated.
