### ISSUE TITLE
Buttons work outside of application, but not within it

### ISSUE THREAD

**Issue by Kolbrandr** [timothycrosley/streamdeck-ui#59]
I have buttons set to switch between scenes on OBS, and they seem to work fine on the desktop. But if I go into say, Civ 6, which I'm trying to record/stream, then the buttons don't actually work anymore.

**Comment by Gazer** [comment]
Check https://github.com/timothycrosley/streamdeck-ui/issues/47#issuecomment-623252357 for a workaround.

**Comment by dodgyrabbit** [comment]
Closing this issue for now, as there is a better solution for directly communicating with OBS in the pipeline. This will avoid the whole switching between apps problem.
