### ISSUE TITLE
Background of the system tray icon is black not transparent

### ISSUE THREAD

**Issue by cros13** [timothycrosley/streamdeck-ui#6]
Background of the system tray icon is black not transparent. Background should be transparent to match themes.

**Comment by xorbital** [comment]
Maybe a black border around the logo so it doesn't vanish on white backgrounds then?

**Comment by xorbital** [comment]
![1px border](https://i.imgur.com/g4tDtJq.png)
Hm, not too great

**Comment by dodgyrabbit** [comment]
Closing for now, we may revisit in future. Will focus on some of the other issues.
