### ISSUE TITLE
Configuring controls and keypresses

### ISSUE THREAD

**Issue by wretanhewe** [timothycrosley/streamdeck-ui#61]
I have installed streamdeck on Manjaro, and it works great, runs and displays and does just what it's supposed to! However, I cannot for the life of me find documentation on what options are, and syntax, for the "command" and "press key" fields are capable of. I've figured out I can put commands into command field, that would normally be runable in a terminal session, like opening programs by name. I might just need to play with it more, but what else is possible, like pointing it to custom scripts or things? I've tried this, and it just throws errors like "no such file or directory", and then the streamdeck itself (Though the UI is just fine) refuses to perform any of the button functions until i force kill and restart Streamdeck.

For the press keys field, I've figured out that I can do shortcuts like "control+n" by writing in exactly this. I suspect alt is "alt", but when I try "control+alt+l" for screen-locking, nothing happens. When I press those keys on my keyboard, it does exactly that, locking the screen. 

Also, I've tried "super" and "meta" for the super/windows key on my keyboard, but that just causes an error forcing me to restart streamdeck. What is that key called, for streamdeck? I also was about to setup volume controls, with a shortcut involving my arrow keys, when I realized I'm not sure how the arrow keys would even be called out in this field.

**Comment by quartersight** [comment]
I suspect that control is ctrl, have you tried that?

**Comment by wretanhewe** [comment]
Yes, using Ctrl works, in that the program doesn't throw an error. And as best I can tell, for the combo of "ctrl+L" or "ctrl+alt+L", will send those keystrokes into whatever program im using, which may or may not do anything.
However, if I use that keystroke on my actual keyboard, it will trigger the global shortcut (im using KDE Plasma) to lock my screen. 
So, I'm unsure how this is effectively simulating a hotkey combination, but... the action doesn't occur. But the action does occur when I just do it normally on my keyboard. 

Somewhat related, I'm still not sure what needs to be written in, to try to press the meta/super/windows key, arrow, or function keys. I've not found any documentation really explaining how those need to be called out.

It seems doing this to trigger hotkeys isn't working terribly well, so unless this is a bug, I'm looking at just having the buttons trigger simple terminal commands, or call bash scripts that can themselves do whatever actions I'm wanting.

**Comment by kC0pter** [comment]
After some minutes of research in the code i found out that the allowed key names are found here: https://pynput.readthedocs.io/en/latest/_modules/pynput/keyboard/_base.html#Key
For the simulated keypresses the pynput lib is used and a gettattr is called on that Key Enum with the key string.
That is also the spot where the program silently crashes if the key doesn't exist.

File: api.py
Line 37 (+ 39)
`keyboard.press(getattr(Key, key_name.lower(), key_name))`

getattr throws an exception if the key doesn't exist.

**Comment by dodgyrabbit** [comment]
> Also, I've tried "super" and "meta" for the super/windows key on my keyboard,
The key you're looking for is `cmd`

> but that just causes an error forcing me to restart streamdeck.
The latest master has better error handling.

Please see the readme help section and known issues for more info on key press feature.
