### ISSUE TITLE
Can't send plus key

### ISSUE THREAD

**Issue by robbieh** [timothycrosley/streamdeck-ui#66]
I've peeked at the code and understand why it doesn't work, but I'd like to be able to send a + as a keypress.

If you don't have time to look, I can take a shot at it. I don't see a clever way to do it. Maybe adding 'plus' as a key in pynput.keyboard.Key? I thought you might have some ideas.

**Comment by dodgyrabbit** [comment]
Been thinking about this one, you can achieve a `+` with

```
shift+=
```

At least on my keyboard, the `=` and `+` signs are on the same key, with `=` being the default. So as per above, `shift` together with `=` will produce a `+`.

Having said that, I'm going to implement a simple change to allow for
```
plus
```
to be used.

**Comment by dodgyrabbit** [comment]
Implemented in 41798ab0b9ad7c6313ec051d826d7348d888493e
