### ISSUE TITLE
Ubuntu 20.04 - Streamdeck UI Crash When Configured App Icon Missing

### ISSUE THREAD

**Issue by mourngrym1969** [timothycrosley/streamdeck-ui#68]
After updating Ubuntu 20.04 to kernel 5.4.0-51, the Streamdeck app would start and indicate an error that an icon for one of the configured app shortcuts was missing from the local app icon location (path is printed to console if run from there). Pressing any button on the Streamdeck itself would cause the USB device to completely reset (found by running 'dmesg' and seeing the disconnect and reconnect of the device logged). 

Was fixed by simply copying any image to the filename in question, which allowed the GUI to come up and the device worked normally at that point. Probably should default to a blank image if any icon previously configured is not found rather than cause a full crash of the device and reset of the connection.

**Comment by dodgyrabbit** [comment]
This has been fixed in 3f6ec6e7d9afbafe6e16ca2b4f073406a60ba584
A message will be displayed every time the icon is accessed but the program won't stop working.
