### ISSUE TITLE
Streamdeck-ui does not sleep the streamdeck display

### ISSUE THREAD

**Issue by cros13** [timothycrosley/streamdeck-ui#7]
Streamdeck-ui does not have an option to sleep the streamdeck display. This is an issue for long term use due to the risk of burn-in.

**Comment by xorbital** [comment]
A small "settings" pop-up with configurable timeouts on lowering the brightness and setting it to 0 would probably be the dream setup then?

**Comment by dodgyrabbit** [comment]
You can give this a try at:
https://github.com/timothycrosley/streamdeck-ui/issues/115

**Comment by dodgyrabbit** [comment]
This has been implemented in v1.1
