### ISSUE TITLE
basic instructions?

### ISSUE THREAD

**Issue by mobev** [timothycrosley/streamdeck-ui#70]
It looks like this may be fairly dead, but if it's still active, I'm looking for some basic directions on how to use the application.  For instance, what is the difference between "Command" and "Press Keys"?  It looks like from other comments that you can't just type the key combination into Press Keys but have to use a description of the keys to press: ctrl+alt_shift+a but there isn't anything that actually says that as far as I've found.

Also, I'm having trouble getting the "switch page" function to work.  It looks like you select a key and then use the Switch Page box to select a page to go to.  This works from the gui, but not on the streamdeck.

My main goal is to just get hotkey bindings working for OBS and to be able to switch pages for additional room for commands.

I'm using the streamdeck XL on Linux Mint 19.3 if that matters.

Thanks for the work that has been put into this and the underlying python library.

morris

**Comment by wretanhewe** [comment]
Im in a similar boat. Navigating pages on the Streamdeck works as i'd expect, but I've found nothing specific for doing anything more complex than a single shift or alt modifier to keystrokes.
It's giving me other issues right now, so I can't check just yet, but the "switch page" I believe was just the action for a button, and then it would navigate as needed. 
Running on Manjaro over here.

**Comment by desrod** [comment]
I can confirm this works fine on the Streamdeck XL itself, as well as in the UI. 

When you configure the button to switch pages (I have Next/Prev page buttons on every page except the first one, which only has a "Next" button, you configure it as follows: 

On the button you create on page 1, set 'Switch Page' to 2, On page 2, create a button that switches back to page 1 (Prev) and another that switches to page 3 (Next), and so on. 

The resulting JSON should look like: 
`"31": {                                                                                                                    
    "write": "",                                                                                                           
    "switch_page": 2,                                                                                                      
    "text": "Next page",                                                                                                   
    "brightness_change": 0,                                                                                                
    "command": ""                                                                                                          
 }`

This worked for me.

**Comment by dodgyrabbit** [comment]
Documentation added in 83f303fd241c9255f1b7833a7b68cf6edb9e57fc
