### ISSUE TITLE
Cross platform?

### ISSUE THREAD

**Issue by Krzmbrzl** [timothycrosley/streamdeck-ui#71]
I know this project is meant to be used on Linux as Elgato's official app is running on Mac and Windows.
Given that the UI is written in Python though I was wondering whether it would also run on these platforms. So the question is: Is this Linux-only or is it actually cross-platform?

**Comment by dodgyrabbit** [comment]
The project's goal was to give Linux users streamdeck UI. However, you are quite correct, it would likely be possible or with relatively little work. The [underlying library](https://github.com/abcminiuser/python-elgato-streamdeck) is cross plat, so is Pyside2. Not the priority right now but feel to try getting this to run on Windows/Mac and submit a PR.
