### ISSUE TITLE
Bug: Buttons append commands

### ISSUE THREAD

**Issue by pixelbrackets** [timothycrosley/streamdeck-ui#74]
Hey,

first off thank you very much for this package! Reading your the blog post about playing around with this gadget was fun. 😀

# What I did

Ubuntu 20.04
Stream Deck Mini

Set commands for 6 Buttons. From `echo "Hello World"` to `chromium-browser https://github.com`.

# What I expected

When I push a button, the command for this button is executed.

# What happend

When I push a button, the commands of all previous buttons are appended. Click on button 4 will execute the command for button 1,2 and 3. Clock on button 3 will execute the command for button 1 and 2.

**Comment by Kitsune-Kuro** [comment]
@pixelbrackets Is this bug still current?

**Comment by pixelbrackets** [comment]
I can't confirm if this is still reproducible in newer versions, because I sold the device due to this bug. Sorry.

**Comment by dodgyrabbit** [comment]
Closing for now, if someone can reproduce this and provide more info, please reopen.
