### ISSUE TITLE
Feature Request: Copy some buttons on all pages

### ISSUE THREAD

**Issue by Saruspete** [timothycrosley/streamdeck-ui#75]
Hello,

I'm just getting started with streamdeck, and would like to use the folders to organize by category.
There's some buttons I'd like to have on all pages, like: 

- Navigate through folders (eg, next/prev folder). That would be nice to select the folders to enable/disable.
- Always have the "play/pause" & "lock workstation" buttons available on the current folder

Thanks a lot for this nice tool !

**Comment by dodgyrabbit** [comment]
Thank you for the feedback. 
As you probably know, this can be achieved using the Page feature and by setting up your buttons on each page.
Realistically, a copy feature may not be implemented. Another alternative would be to copy/paste the button definitions directly in the settings file:

1. Exit streamdeck
2. Make a backup of `~\.streamdeck_ui.json`
3. Open it in a text editor. The format is not too complex. You'll see under the "Buttons" property is an object with "0" through "9" for each page. Under each of those, are your button definitions.
4. Carefully copy/paste the buttons from one page to the next, ensuring that file structure remains sound.
5. Start streamdeck
Hopefully this helps.
