### ISSUE TITLE
Issue with startin streamdeck on Linux Mint 19.2

### ISSUE THREAD

**Issue by derrickmehaffy** [timothycrosley/streamdeck-ui#8]
Error Message after install trying to start with `streamdeck` used the recommended script from the README.md. Stream deck just shows their giant logo across all the keys. Let me know if you need more information

```
dmehaffy:~$ streamdeck
Traceback (most recent call last):
  File "/usr/local/bin/streamdeck", line 11, in <module>
    sys.exit(start())
  File "/usr/local/lib/python3.6/dist-packages/streamdeck_ui/gui.py", line 266, in start
    for deck_id, deck in api.open_decks().items():
  File "/usr/local/lib/python3.6/dist-packages/streamdeck_ui/api.py", line 99, in open_decks
    for deck in DeviceManager.DeviceManager().enumerate():
  File "/home/dmehaffy/.local/lib/python3.6/site-packages/StreamDeck/DeviceManager.py", line 75, in enumerate
    found_devices = self.transport.enumerate(vid=vid, pid=pid)
  File "/home/dmehaffy/.local/lib/python3.6/site-packages/StreamDeck/Transport/HIDAPI.py", line 161, in enumerate
    devices = hid.enumerate(vendor_id=vid, product_id=pid)
TypeError: enumerate() got an unexpected keyword argument 'vendor_id'
```

![image](https://user-images.githubusercontent.com/8593673/67369699-58e1bb00-f52e-11e9-9d42-42869617f1fc.png)

# System
Distributor ID:	LinuxMint
Description:	Linux Mint 19.2 Tina
Release:	19.2
Codename:	tina
Kernel: 4.15.0-65-generic

**Comment by mauilion** [comment]
Same issue on my ubuntu setup :/
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
```

**Comment by derrickmehaffy** [comment]
What's odd is I have another system running linux mint and didn't have the issue :thinking:

**Comment by messy-garage** [comment]
Same issue here, tried on Ubuntu 18.04.3 and 19.10
walked thru the installation steps with no issues, but trying to start from the command line gets

<pre><font color="#8AE234"><b>ale@P-body</b></font>:<font color="#729FCF"><b>~</b></font>$ streamdeck 
Traceback (most recent call last):
  File &quot;/home/ale/.local/bin/streamdeck&quot;, line 11, in &lt;module&gt;
    sys.exit(start())
  File &quot;/home/ale/.local/lib/python3.6/site-packages/streamdeck_ui/gui.py&quot;, line 269, in start
    build_device(ui)
  File &quot;/home/ale/.local/lib/python3.6/site-packages/streamdeck_ui/gui.py&quot;, line 199, in build_device
    build_buttons(ui, page)
  File &quot;/home/ale/.local/lib/python3.6/site-packages/streamdeck_ui/gui.py&quot;, line 129, in build_buttons
    deck = api.get_deck(deck_id)
  File &quot;/home/ale/.local/lib/python3.6/site-packages/streamdeck_ui/api.py&quot;, line 133, in get_deck
    return {&quot;type&quot;: decks[deck_id].deck_type(), &quot;layout&quot;: decks[deck_id].key_layout()}
KeyError: None
</pre>

not a programmer, but please let me know if other info are needed to help investigate

**Comment by remlap** [comment]
I am suffering this error too, I have a streamdeck coming from the states and want to being to use it.

**Comment by remlap** [comment]
I just received my streamdeck and works soon as I plugged it in. I assumed the GUI would work without.

**Comment by dodgyrabbit** [comment]
Old issue. Closing for now. There are some related fixes in the pipeline.

**Comment by Br3nda** [comment]
Still happening on the latest stream-deck

```
  File "/home/brenda/.local/bin/streamdeck", line 8, in <module>
    sys.exit(start())
  File "/home/brenda/.local/lib/python3.10/site-packages/streamdeck_ui/gui.py", line 269, in start
    build_device(ui)
  File "/home/brenda/.local/lib/python3.10/site-packages/streamdeck_ui/gui.py", line 199, in build_device
    build_buttons(ui, page)
  File "/home/brenda/.local/lib/python3.10/site-packages/streamdeck_ui/gui.py", line 129, in build_buttons
    deck = api.get_deck(deck_id)
  File "/home/brenda/.local/lib/python3.10/site-packages/streamdeck_ui/api.py", line 133, in get_deck
    return {"type": decks[deck_id].deck_type(), "layout": decks[deck_id].key_layout()}
KeyError: None
```
