### ISSUE TITLE
No text is being rendered in the UI

### ISSUE THREAD

**Issue by Anton-4** [timothycrosley/streamdeck-ui#81]
Clicking the drop down in the top left corner prints the following error in the terminal:
```
QFont::setPointSizeF: Point size <= 0 (-0.600000), must be greater than 0
```

I'm using KDE neon 5.20 based on Ubuntu 20.04

I'm going to try to debug this and will post my solution.

**Comment by dodgyrabbit** [comment]
Closing for now. If you have more information @Anton-4 , please feel free to reopen.
