### ISSUE TITLE
Remove / Reset Streamdeck

### ISSUE THREAD

**Issue by lee11lee** [timothycrosley/streamdeck-ui#82]
Hi,

I'm using a new streamdeck, but streamdeck-ui is still outputting the "Likely unplugged" warning message.
How can I remove all settings of a old streamdeck from streamdeck-ui?

Also I'd like to reset a streamdeck, how can I do that?

Thx, so much for developing this, I'm using it for a year now and this saves me
so much time at work!

cheers
lee

**Comment by desrod** [comment]
You should be able to just rm your ~/.streamdeck_ui.json file in your $HOME to start with a clean, empty interface.
