### ISSUE TITLE
How to use Press keys

### ISSUE THREAD

**Issue by rogoit** [timothycrosley/streamdeck-ui#88]
Hi, 

I try to add a take a screenshot command on Ubunto 20. I checked
SHIFT+CTRL+PRINT
SHIFT-CTRL-PRINT
shift ctrl print
shift-ctrl-print

Maybe you can give me a hint
Thx
Roland

**Comment by desrod** [comment]
I gave this a try, and it fails here as well, but I also have my window manager (currently xfce4) bound to the Print key, and it runs `/usr/bin/xfce4-screenshooter -r -s ~/Downloads/` when pressed, so I just set up a button in streamdeck to run the same command. Problem solved! 

Incidentally, if you want some sample code that will show you which keys PyQt is intercepting when pressed, this will work: 

```
#!/usr/bin/env python3

import sys

from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QWidget

keymap = {}
for key, value in vars(Qt).items():
    if isinstance(value, Qt.Key):
        keymap[value] = key.partition("_")[2]

modmap = {
    Qt.ControlModifier: keymap[Qt.Key_Control],
    Qt.AltModifier: keymap[Qt.Key_Alt],
    Qt.ShiftModifier: keymap[Qt.Key_Shift],
    Qt.MetaModifier: keymap[Qt.Key_Meta],
    Qt.GroupSwitchModifier: keymap[Qt.Key_AltGr],
    Qt.KeypadModifier: keymap[Qt.Key_NumLock],
}


def keyevent_to_string(event):
    sequence = []
    for modifier, text in modmap.items():
        if event.modifiers() & modifier:
            sequence.append(text)
    key = keymap.get(event.key(), event.text())
    if key not in sequence:
        sequence.append(key)
    return "+".join(sequence)


class Window(QWidget):
    def keyPressEvent(self, event):
        print(keyevent_to_string(event))


if __name__ == "__main__":

    app = QApplication(sys.argv)
    window = Window()
    window.setGeometry(600, 100, 300, 200)
    window.show()
    sys.exit(app.exec_())
```

**Comment by rogoit** [comment]
Looks a bit tricky....where is the file. I also think that this is a feature and i only wrote the wrong words for it ;) 

Thx for your answer an a healthy and good start in the new year ;)

**Comment by kazie** [comment]
I wrote like in the guide:
```
Ctrl+a
```
And got it to work, my guess is that the problem is that you didn't write `Ctrl` `Alt` `Print` as these.
I got how to write it (first letter capital, rest not) from the GIF on the presentation.

When it fails, I see that it stops working completely until I re-plug it. So for example writing `print` instead of `print_screen` will disable all buttons.

---

All button names are here:
https://pynput.readthedocs.io/en/latest/keyboard.html
As that seems to be the library they use.

**Comment by hutber** [comment]
Oddly I'm also having interesting problems with keyboard shortcuts. Which means any commands :D

**Comment by dodgyrabbit** [comment]
I suggest try using the **command** feature to take a screenshot.
On Ubuntu 2004 you can use `gnome-screenshot`. You can also [pass other options](https://askubuntu.com/a/194470/328384).

There are some issues with the key press stuff - please see the readme for some known issues and workarounds. Latest master has better error handling and shows you the error if something doesn't work.
