### ISSUE TITLE
Project still alive and of interest for the owner?

### ISSUE THREAD

**Issue by Boldie** [timothycrosley/streamdeck-ui#89]
As I want to make some additions I saw a long list of issues and pull requests: Is this project of your interest or is it abandoned after it was born?

If it is no longer of interest, please consider creating a new github organisation and move the development to some interested peoples there. So this wonderfull piece of work can have a centralized workplace.

**Comment by desrod** [comment]
Feel free to fork the repository, proposed and commit your changes/additions and PR them across. That's how this works.

**Comment by dodgyrabbit** [comment]
Project is still alive and I'll be helping getting some of the community contributions merged over the next few weeks.
Thanks @Boldie for your interest and williness to make PRs.
