### ISSUE TITLE
Keypresses not working

### ISSUE THREAD

**Issue by t3838d4** [timothycrosley/streamdeck-ui#97]
"Press Keys" nor "Write Text" does not work outside streamdeck_ui window. 
I guess this is because of Wayland or because some Python dependency needing sudo. 

Any known fix to this? 

Using latest Fedora on Wayland.

**Comment by jdob** [comment]
Same issue here, I can configure the deck, but none of the command or press keys options are working. I'm on Fedora 33, but I have Wayland disabled.

**Comment by jdob** [comment]
Update: They seem to be working for me. If I have an error on what they do (previously, they called scripts that didn't start with "#!/bin/bash") all buttons stop working.

My sanity check is to have a button with the command "echo -ne '\007'". That will play a system beep and it's what I use to double check that the deck is behaving.

**Comment by pklaus** [comment]
So the library/Python package used for keypresses is pynput. It seems to only support sending keypresses to the application which is currently upfront. In addition, any key combination involding the `cmd` key doesn't work for me. So while `ctrl+alt+o` works, `ctrl+alt+cmd+o` does not. That's on my machine running KDE5/Plasma on an up-to-date Arch Linux machine.

**Comment by dodgyrabbit** [comment]
Summarizing the situation:

- We use [pynput](https://github.com/moses-palmer/pynput) for handling keypresses
- Support for [Wayland is lacking](https://github.com/moses-palmer/pynput/issues/189)
- The [currently released version](https://pypi.org/project/streamdeck-ui/) (1.0.2) for streamdeck-ui has no error handling. As a result, failure on any action (command, text, press keys etc)  would make everything else also stop working. This makes it hard to determine what's going on as per @jdob. 
- Ubuntu and Linux Mint uses X and you should be able to use Press keys and Write Text.

The currently recommended workaround (thanks @hutber) is to use the Command feature, to run a script or program, which in turn can execute the desired keypresses. The command feature does not rely on pynput and therefore avoids the problem. 
https://github.com/timothycrosley/streamdeck-ui/issues/47#issuecomment-776036065

Steps to close this issue:
- Improve documentation (add "known issues")
- Improve error handling

In my experience, most value comes from the **Command** feature anyways.

**Comment by dodgyrabbit** [comment]
Updated the readme in 83f303fd241c9255f1b7833a7b68cf6edb9e57fc.
