### ISSUE TITLE
Feature request: start-minimized

### ISSUE THREAD

**Issue by HeyyItsBran** [timothycrosley/streamdeck-ui#98]
Could you add a command line argument such as `streamdeck --start-minimized` to start the program in the tray, would be useful for starting on boot

Thanks!!

**Comment by obook** [comment]
You can edit the gui.py file, in my case is .local/lib/python3.8/site-packages/streamdeck_ui/gui.py and comment the line 284 : 

`#    main_window.show()`

Regards,
Olivier

**Comment by ToeiRei** [comment]
Not everyone wants to modify the source - so it would be great to have that minimized parameter
